#!/usr/bin/env python3
"""
Finnhub Bond Yield Curve — Auto-generated by NightBuilder
Finnhub bond yield curve data for US Treasuries and corporate bonds.

Source: https://finnhub.io/docs/api/bond-yield-curve
Sample endpoint: https://finnhub.io/api/v1/bond/yield-curve?token=YOUR_TOKEN
Category: Fixed Income & Credit
Free tier: True
Update frequency: real-time

Integration approach: HTTP GET requests with free API key.
"""

import requests
import os
import time
from datetime import datetime, timedelta
from typing import Dict, Any, Optional, List

BASE_URL = "https://finnhub.io/api/v1"

def get_api_key() -> str:
    """Get Finnhub API key from env or fallback to sandbox."""
    key = os.getenv("FINNHUB_API_KEY")
    if key:
        return key
    # Fallback sandbox key (demo data)
    return "sandbox_cskuej4r01qkhj7674h1"  # Note: Use real key from .env

def get_yield_curve() -> Dict[str, Any]:
    """
    Get US Treasury and corporate bond yield curve data.
    
    Returns:
        dict: Yield curve data or error.
    """
    url = f"{BASE_URL}/bond/yield-curve"
    params = {"token": get_api_key()}
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        return data
    except requests.RequestException as e:
        return {"error": f"Request failed: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}

def get_bond_profile(isin: str) -> Dict[str, Any]:
    """
    Get bond profile by ISIN.
    
    Args:
        isin: Bond ISIN (e.g., "US9128283M65")
    
    Returns:
        dict: Bond profile or error.
    """
    url = f"{BASE_URL}/bond/profile"
    params = {"isin": isin, "token": get_api_key()}
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        return data
    except requests.RequestException as e:
        return {"error": f"Request failed: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}

def get_economic_calendar(from_date: Optional[str] = None, to_date: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Get economic calendar events.
    
    Args:
        from_date: Start date YYYY-MM-DD (default today)
        to_date: End date YYYY-MM-DD (default today + 7 days)
    
    Returns:
        list: Calendar events or error dict.
    """
    if from_date is None:
        from_date = datetime.now().strftime("%Y-%m-%d")
    if to_date is None:
        to_date = (datetime.now() + timedelta(days=7)).strftime("%Y-%m-%d")
    
    url = f"{BASE_URL}/calendar/economic"
    params = {"from": from_date, "to": to_date, "token": get_api_key()}
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        return data.get("economicCalendar", [])
    except requests.RequestException as e:
        return [{"error": f"Request failed: {str(e)}"}]
    except Exception as e:
        return [{"error": f"Unexpected error: {str(e)}"}]

def get_market_status(exchange: str = "US") -> Dict[str, Any]:
    """
    Get market status (open/closed).
    
    Args:
        exchange: Exchange code (default "US")
    
    Returns:
        dict: Market status or error.
    """
    url = f"{BASE_URL}/stock/us/market-status"
    params = {"exchange": exchange, "token": get_api_key()}
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        return data
    except requests.RequestException as e:
        return {"error": f"Request failed: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}

def get_crypto_candles(symbol: str, resolution: str = "D", from_ts: Optional[int] = None, to_ts: Optional[int] = None) -> Dict[str, Any]:
    """
    Get crypto candles.
    
    Args:
        symbol: Crypto symbol (e.g., "BINANCE:BTCUSDT")
        resolution: 1,5,15,30,60,H,D,W,M
        from_ts: Unix timestamp start
        to_ts: Unix timestamp end
    
    Returns:
        dict: Candles data {'c': [...], 'h': [...], etc.} or error.
    """
    if from_ts is None:
        from_ts = int((time.time() - 86400 * 30) * 1000) // 1000  # 30 days ago
    if to_ts is None:
        to_ts = int(time.time())
    
    url = f"{BASE_URL}/crypto/candle"
    params = {
        "symbol": symbol,
        "resolution": resolution,
        "from": from_ts,
        "to": to_ts,
        "token": get_api_key()
    }
    try:
        resp = requests.get(url, params=params, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        if data.get("s") == "no_data":
            return {"error": "No data available"}
        return data
    except requests.RequestException as e:
        return {"error": f"Request failed: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}

if __name__ == "__main__":
    print("Finnhub Bond Yield Curve module loaded.")
    print(get_yield_curve())
