export interface Phase {
  id: number;
  name: string;
  description: string;
  status: "done" | "next" | "planned";
  category: string;
  loc?: number; // lines of code
}

export const phases: Phase[] = [
  // Completed
  { id: 1, name: "Core Market Data", description: "Real-time prices, SEC EDGAR filings, news sentiment, caching layer, CLI", status: "done", category: "Foundation", loc: 82 },
  { id: 2, name: "Enhanced Data", description: "Options chains with Greeks, earnings calendar, macro indicators, dividends, ETF holdings", status: "done", category: "Foundation", loc: 398 },
  { id: 3, name: "Alternative Data", description: "Social sentiment (Reddit/StockTwits), congress trades, short interest, technical analysis", status: "done", category: "Alt Data", loc: 355 },
  { id: 4, name: "Multi-Asset Coverage", description: "Cryptocurrency via CoinGecko, commodities, forex, analyst ratings, company profiles, screener", status: "done", category: "Multi-Asset", loc: 500 },
  { id: 5, name: "Earnings Transcripts NLP", description: "Parse 8-K/call transcripts, extract key quotes, guidance changes, management sentiment", status: "done", category: "Intelligence", loc: 296 },
  { id: 6, name: "Options Flow Scanner", description: "Unusual activity alerts, dark pool prints, sweep detection, smart money tracking", status: "done", category: "Derivatives", loc: 337 },
  { id: 7, name: "Factor Model Engine", description: "Momentum, value, quality, size, volatility factor scoring for any stock", status: "done", category: "Quant", loc: 398 },
  { id: 8, name: "Portfolio Analytics", description: "Sharpe, Sortino, max drawdown, correlation matrix, Value-at-Risk calculations", status: "done", category: "Quant", loc: 381 },
  { id: 9, name: "Backtesting Framework", description: "Event-driven backtester with realistic fills, slippage modeling, commission tracking", status: "done", category: "Quant", loc: 397 },
  { id: 10, name: "Smart Alerts", description: "Price alerts, volume spikes, RSI thresholds, earnings date reminders with multi-channel delivery", status: "done", category: "Infrastructure", loc: 526 },
  { id: 11, name: "Patent Tracking", description: "USPTO patent filings, R&D velocity scoring, innovation index for any company", status: "done", category: "Alt Data", loc: 337 },
  { id: 12, name: "Job Posting Signals", description: "Hiring velocity as leading indicator, department growth analysis, geographic expansion tracking", status: "done", category: "Alt Data", loc: 410 },
  { id: 13, name: "Supply Chain Mapping", description: "SEC NLP for supplier/customer relationships, dependency graphs, concentration risk", status: "done", category: "Alt Data", loc: 451 },
  { id: 14, name: "Weather & Agriculture", description: "NOAA weather data, crop conditions, energy demand signals for ag/energy sectors", status: "done", category: "Alt Data", loc: 495 },
  { id: 15, name: "Bond Analytics", description: "Yield curves, credit spreads, duration, convexity analysis for fixed income", status: "done", category: "Fixed Income", loc: 439 },
  { id: 16, name: "SEC NLP Analysis", description: "Risk factor extraction, MD&A sentiment scoring, change detection across filings", status: "done", category: "Intelligence", loc: 505 },
  { id: 17, name: "IPO & SPAC Tracker", description: "Upcoming IPOs, SPAC arbitrage opportunities, lock-up expiry dates", status: "done", category: "Events", loc: 462 },
  { id: 18, name: "M&A Deal Flow", description: "Announced deals, merger arb spreads, completion probability scoring", status: "done", category: "Events", loc: 497 },
  { id: 19, name: "Activist Investor Tracking", description: "13D filings, campaign tracking, activist target identification", status: "done", category: "Alt Data", loc: 456 },
  { id: 20, name: "ESG Scoring", description: "Environmental, social, governance composite scores and peer comparison", status: "done", category: "Alt Data", loc: 430 },
  { id: 21, name: "Quant Factor Zoo", description: "Replicate 400+ published academic factors with statistical validation", status: "done", category: "Quant", loc: 1208 },
  { id: 22, name: "Market Microstructure", description: "Bid-ask spreads, order flow imbalance, liquidity scoring, market maker activity", status: "done", category: "Quant", loc: 492 },
  { id: 23, name: "AI Research Reports", description: "One-click LLM-generated equity research pulling from all data sources", status: "done", category: "Intelligence", loc: 409 },
  { id: 24, name: "Data Quality Monitor", description: "Automated staleness checks, source health validation, alert triggers for broken feeds", status: "done", category: "Infrastructure", loc: 380 },
  { id: 25, name: "Real-time Streaming", description: "WebSocket feeds for live prices via Polygon, Finnhub, Alpaca. Level 2 quotes", status: "done", category: "Infrastructure", loc: 332 },
  { id: 26, name: "ML Earnings Predictor", description: "Random Forest + XGBoost ensemble predicting earnings beats/misses with 77% accuracy", status: "done", category: "ML/AI", loc: 402 },
  { id: 27, name: "Correlation Heatmaps", description: "Cross-asset regime change detection across 22 ETFs with Z-score anomaly flagging", status: "done", category: "Quant", loc: 499 },
  { id: 30, name: "CDS Spreads", description: "Sovereign and corporate credit risk signals from credit default swap markets", status: "done", category: "Fixed Income", loc: 486 },
  { id: 31, name: "Fama-French Regression", description: "Statistical factor attribution and multi-factor risk decomposition", status: "done", category: "Quant", loc: 390 },
  { id: 29, name: "Hedge Fund 13F Replication", description: "Clone top fund positions, track quarterly changes, smart money flow analysis", status: "done", category: "Alt Data", loc: 681 },
  { id: 28, name: "Options GEX Tracker", description: "Dealer gamma exposure positioning, pin risk at major strikes, hedging flow analysis", status: "done", category: "Derivatives", loc: 498 },
  // Next up
  // Planned
  { id: 32, name: "Pairs Trading Signals", description: "Cointegration detection, mean reversion opportunities, spread monitoring", status: "done", category: "Quant", loc: 518 },
  { id: 33, name: "Sector Rotation Model", description: "Economic cycle indicators, relative strength rotation strategies", status: "done", category: "Quant", loc: 411 },
  { id: 34, name: "Monte Carlo Simulation", description: "Scenario analysis, probabilistic forecasting, tail risk modeling", status: "done", category: "Quant", loc: 518 },
  { id: 35, name: "Kalman Filter Trends", description: "Adaptive moving averages, regime change signals with state-space models", status: "done", category: "Quant", loc: 575 },
  { id: 36, name: "Black-Litterman Allocation", description: "Combine market equilibrium with investor views for portfolio construction", status: "done", category: "Quant", loc: 481 },
  { id: 37, name: "Walk-Forward Optimization", description: "Out-of-sample strategy tuning with rolling windows to prevent overfitting", status: "done", category: "Quant", loc: 421 },
  { id: 38, name: "Multi-Timeframe Analysis", description: "Combine signals from daily/weekly/monthly charts for confirmation", status: "done", category: "Quant", loc: 476 },
  { id: 39, name: "Order Book Depth", description: "Level 2 data analysis, bid-ask imbalance, hidden liquidity detection", status: "done", category: "Quant", loc: 452 },
  { id: 40, name: "Smart Alert Delivery", description: "Multi-channel notifications (email, SMS, Discord, Telegram) with rate limiting", status: "done", category: "Infrastructure", loc: 619 },
  { id: 41, name: "Alert Backtesting", description: "Test alert strategies historically, measure signal quality, false positive rates", status: "done", category: "Infrastructure", loc: 550 },
  { id: 42, name: "Custom Alert DSL", description: "Domain-specific language for complex multi-condition alert rules", status: "done", category: "Infrastructure", loc: 658 },
  { id: 43, name: "Crypto On-Chain Analytics", description: "Whale wallet tracking, token flows, DEX volume, gas fee analysis", status: "planned", category: "Multi-Asset" },
  { id: 44, name: "Commodity Futures Curves", description: "Contango/backwardation signals, roll yields, term structure analysis", status: "planned", category: "Multi-Asset" },
  { id: 45, name: "Fed Policy Prediction", description: "FOMC analysis, dot plot tracking, rate hike probability scoring", status: "planned", category: "ML/AI" },
  { id: 46, name: "Satellite Imagery", description: "Parking lot occupancy, shipping containers, construction activity tracking", status: "planned", category: "Alt Data" },
  { id: 47, name: "Earnings Call NLP", description: "Tone analysis, linguistic markers, management confidence, question-dodging detection", status: "planned", category: "Intelligence" },
  { id: 48, name: "Peer Network Analysis", description: "Interconnected company relationships, revenue dependency mapping, systemic risk", status: "planned", category: "Intelligence" },
  { id: 49, name: "Political Risk Scoring", description: "Geopolitical events, sanctions tracking, regulatory change impact modeling", status: "planned", category: "Alt Data" },
  { id: 50, name: "Product Launch Tracker", description: "Social buzz, pre-order velocity, review sentiment for new product launches", status: "planned", category: "Alt Data" },
  { id: 51, name: "Executive Compensation", description: "Pay-for-performance correlation, peer comparison, shareholder alignment metrics", status: "planned", category: "Alt Data" },
  { id: 52, name: "Revenue Quality Analysis", description: "Cash flow vs earnings divergence, DSO trends, channel stuffing detection", status: "planned", category: "Intelligence" },
  { id: 53, name: "Peer Earnings Comparison", description: "Beat/miss patterns, guidance trends, analyst estimate dispersion", status: "planned", category: "Events" },
  { id: 54, name: "Crypto Correlation Indicators", description: "BTC dominance, altcoin seasonality, DeFi TVL impact on tech stocks", status: "planned", category: "Multi-Asset" },
  { id: 55, name: "Tax Loss Harvesting", description: "Identify opportunities, track wash sale rules, estimate tax savings", status: "planned", category: "Quant" },
  { id: 56, name: "Share Buyback Analysis", description: "Authorization vs execution, dilution impact, return on buyback calculation", status: "planned", category: "Events" },
  { id: 57, name: "Dividend Sustainability", description: "Payout ratio trends, FCF coverage, dividend cut probability modeling", status: "planned", category: "Events" },
  { id: 58, name: "Institutional Ownership", description: "13F changes, whale accumulation/distribution, smart money flow patterns", status: "planned", category: "Alt Data" },
  { id: 59, name: "Earnings Quality Metrics", description: "Accruals ratio, Beneish M-Score, Altman Z-Score for fraud/distress detection", status: "planned", category: "Intelligence" },
  { id: 60, name: "Sector Performance Attribution", description: "Decompose returns into sector allocation vs stock selection effects", status: "planned", category: "Quant" },
  { id: 61, name: "Dark Pool Tracker", description: "Block trade detection, institutional accumulation patterns, hidden liquidity", status: "planned", category: "Alt Data" },
  { id: 62, name: "Estimate Revision Tracker", description: "Analyst upgrades/downgrades velocity, estimate momentum indicators", status: "planned", category: "Events" },
  { id: 63, name: "Corporate Action Calendar", description: "Dividend ex-dates, splits, spin-offs, rights offerings with impact analysis", status: "planned", category: "Events" },
  { id: 64, name: "Convertible Bond Arbitrage", description: "Conversion premium analysis, implied volatility, delta hedging opportunities", status: "planned", category: "Fixed Income" },
  { id: 65, name: "Short Squeeze Detector", description: "High short interest + low float + technical squeeze signals", status: "planned", category: "Alt Data" },
  { id: 66, name: "Market Regime Detection", description: "Volatility clustering, correlation breakdowns, risk-on vs risk-off identification", status: "planned", category: "Quant" },
  { id: 67, name: "Activist Success Predictor", description: "ML model trained on historical activist campaign outcomes and governance scores", status: "planned", category: "ML/AI" },
  { id: 68, name: "13D/13G Filing Alerts", description: "Real-time webhook notifications for new activist filings and stake changes", status: "planned", category: "Events" },
  { id: 69, name: "Proxy Fight Tracker", description: "ISS/Glass Lewis recommendations, shareholder voting, proxy contest outcomes", status: "planned", category: "Events" },
  { id: 70, name: "Greenwashing Detection", description: "NLP analysis of ESG reports vs actual metrics, identify inconsistencies", status: "planned", category: "Intelligence" },
  { id: 71, name: "Sustainability-Linked Bonds", description: "Monitor SLB issuance, KPI achievement, coupon step-up triggers", status: "planned", category: "Fixed Income" },
  { id: 72, name: "Climate Risk Scoring", description: "Physical risk (floods, hurricanes), transition risk (carbon pricing), scenario analysis", status: "planned", category: "Alt Data" },
  { id: 73, name: "Factor Timing Model", description: "Regime detection for when factors work, adaptive factor rotation", status: "planned", category: "ML/AI" },
  { id: 74, name: "ML Factor Discovery", description: "Automated discovery of new predictive factors with feature engineering", status: "planned", category: "ML/AI" },
  { id: 75, name: "Transaction Cost Analysis", description: "Market impact estimation, bid-ask modeling, execution optimization for large trades", status: "planned", category: "Quant" },
  { id: 76, name: "AI Earnings Call Analyzer", description: "Real-time tone detection, hesitation patterns, executive confidence scoring via LLM", status: "planned", category: "ML/AI" },
  { id: 77, name: "Cross-Exchange Arbitrage", description: "Price discrepancies across NYSE/NASDAQ/IEX/CBOE with execution optimization", status: "planned", category: "Quant" },
  { id: 78, name: "Regulatory Event Calendar", description: "FOMC, CPI, GDP tracking with market reaction backtests and volatility forecasts", status: "planned", category: "Events" },
  { id: 79, name: "PDF Report Exporter", description: "Convert markdown reports to professional PDF with charts and email delivery", status: "planned", category: "Infrastructure" },
  { id: 80, name: "Alert Backtesting Dashboard", description: "Visualize historical alert performance with profit factor and Sharpe ratio", status: "planned", category: "Infrastructure" },
  { id: 81, name: "Portfolio Construction Tool", description: "MPT optimizer, Black-Litterman, ESG constraints, tax-aware rebalancing", status: "planned", category: "Quant" },
  { id: 82, name: "Live Earnings Transcription", description: "Stream earnings calls, transcribe with Whisper, extract signals in real-time", status: "planned", category: "ML/AI" },
  { id: 83, name: "Smart Data Prefetching", description: "ML predicts which data will be requested next, preloads during idle", status: "planned", category: "Infrastructure" },
  { id: 84, name: "Multi-Source Reconciliation", description: "Compare data across sources, flag discrepancies, confidence-based voting", status: "planned", category: "Infrastructure" },
  { id: 85, name: "Neural Price Prediction", description: "LSTM/Transformer models for multi-horizon forecasting with uncertainty quantification", status: "planned", category: "ML/AI" },
  { id: 86, name: "Order Book Imbalance", description: "Level 3 data, predict short-term price movements from bid/ask imbalances", status: "planned", category: "Quant" },
  { id: 87, name: "Correlation Anomaly Detector", description: "Identify unusual correlation breakdowns, detect regime shifts, flag arbitrage", status: "planned", category: "ML/AI" },
  { id: 88, name: "Deep Learning Sentiment", description: "FinBERT for earnings calls, SEC filings, news with entity-level sentiment", status: "planned", category: "ML/AI" },
  { id: 89, name: "Volatility Surface Modeling", description: "IV smile/skew analysis, volatility arbitrage, straddle/strangle scanner", status: "planned", category: "Derivatives" },
  { id: 90, name: "ML Stock Screening", description: "Multi-factor ML ranking with walk-forward validation and auto-rebalancing", status: "planned", category: "ML/AI" },
  { id: 91, name: "Insider Trading Network", description: "Map insider relationships, detect coordinated buying/selling clusters", status: "planned", category: "Alt Data" },
  { id: 92, name: "Earnings Quality Forensics", description: "Deep accounting red flag detection with Beneish M-Score and fraud probability", status: "planned", category: "Intelligence" },
  { id: 93, name: "Social Sentiment Spike Detector", description: "Real-time Twitter/Reddit surge detection, meme stock momentum, pump detection", status: "planned", category: "ML/AI" },
];

export const dataSources = [
  { name: "Yahoo Finance", icon: "📈", type: "Market Data", desc: "Real-time & historical prices, options, fundamentals", status: "active", modules: ["prices", "options", "technicals", "dividends", "earnings", "company_profile", "screener"] },
  { name: "SEC EDGAR", icon: "📑", type: "Regulatory", desc: "10-K, 10-Q, 8-K filings, insider transactions", status: "active", modules: ["sec_edgar", "sec_nlp", "earnings_transcripts", "activist_investor_tracking"] },
  { name: "CoinGecko", icon: "₿", type: "Crypto", desc: "Cryptocurrency prices, market cap, volume", status: "active", modules: ["crypto"] },
  { name: "Google News RSS", icon: "📰", type: "News", desc: "Real-time news aggregation with NLP sentiment", status: "active", modules: ["news_sentiment"] },
  { name: "FRED (Federal Reserve)", icon: "🏦", type: "Macro", desc: "GDP, CPI, unemployment, interest rates", status: "active", modules: ["macro"] },
  { name: "USPTO", icon: "💡", type: "Alt Data", desc: "Patent filings, R&D velocity", status: "active", modules: ["patent_tracking"] },
  { name: "NOAA", icon: "🌾", type: "Alt Data", desc: "Weather data, crop conditions, energy demand", status: "active", modules: ["weather_agriculture"] },
  { name: "Reddit/StockTwits", icon: "💬", type: "Social", desc: "Social sentiment, retail investor attention", status: "active", modules: ["social_sentiment"] },
  { name: "Congressional Disclosures", icon: "🏛️", type: "Alt Data", desc: "Politician trading disclosures", status: "active", modules: ["congress_trades"] },
  { name: "Polygon.io", icon: "📡", type: "Streaming", desc: "Real-time WebSocket price feeds", status: "active", modules: ["streaming"] },
  { name: "Finnhub", icon: "📡", type: "Streaming", desc: "Multi-market streaming data", status: "active", modules: ["streaming"] },
  { name: "Alpaca", icon: "📡", type: "Streaming", desc: "Commission-free trading data feeds", status: "active", modules: ["streaming"] },
  { name: "X.ai (Grok)", icon: "🤖", type: "AI/LLM", desc: "Research report synthesis, earnings analysis", status: "active", modules: ["research_reports"] },
];

export const ideaGeneration = {
  title: "How We Generate the Roadmap",
  process: [
    { step: "🔬 Academic Research", desc: "Every new phase references published finance papers — factor models, market microstructure theory, behavioral finance" },
    { step: "🏦 Institutional Inspiration", desc: "Features modeled after Bloomberg Terminal, FactSet, Capital IQ, and Refinitiv capabilities" },
    { step: "🤖 AI Self-Evolution", desc: "After each phase, the build agent suggests 3 new features based on what it just built — compounding innovation" },
    { step: "📊 Data Source Expansion", desc: "Each new data source unlocks multiple derived modules — e.g., SEC filings → NLP → supply chain → activist tracking" },
    { step: "🎯 User Signal", desc: "Real trading needs drive priorities — what would a quant trader actually use at 4am before markets open?" },
    { step: "🔗 Cross-Module Synergy", desc: "New phases often combine existing modules — e.g., ML earnings predictor uses options flow + sentiment + technicals" },
  ],
};
