export interface Phase {
  id: number;
  name: string;
  description: string;
  status: "done" | "next" | "planned";
  category: string;
  loc?: number; // lines of code
}

export const phases: Phase[] = [
  // ============ COMPLETED (1-47) ============
  { id: 1, name: "Core Market Data", description: "Real-time prices, SEC EDGAR filings, news sentiment, caching layer, CLI", status: "done", category: "Foundation", loc: 82 },
  { id: 2, name: "Enhanced Data", description: "Options chains with Greeks, earnings calendar, macro indicators, dividends, ETF holdings", status: "done", category: "Foundation", loc: 398 },
  { id: 3, name: "Alternative Data", description: "Social sentiment (Reddit/StockTwits), congress trades, short interest, technical analysis", status: "done", category: "Alt Data", loc: 355 },
  { id: 4, name: "Multi-Asset Coverage", description: "Cryptocurrency via CoinGecko, commodities, forex, analyst ratings, company profiles, screener", status: "done", category: "Multi-Asset", loc: 500 },
  { id: 5, name: "Earnings Transcripts NLP", description: "Parse 8-K/call transcripts, extract key quotes, guidance changes, management sentiment", status: "done", category: "Intelligence", loc: 296 },
  { id: 6, name: "Options Flow Scanner", description: "Unusual activity alerts, dark pool prints, sweep detection, smart money tracking", status: "done", category: "Derivatives", loc: 368 },
  { id: 7, name: "Factor Model Engine", description: "Momentum, value, quality, size, volatility factor scoring for any stock", status: "done", category: "Quant", loc: 398 },
  { id: 8, name: "Portfolio Analytics", description: "Sharpe, Sortino, max drawdown, correlation matrix, Value-at-Risk calculations", status: "done", category: "Quant", loc: 381 },
  { id: 9, name: "Backtesting Framework", description: "Event-driven backtester with realistic fills, slippage modeling, commission tracking", status: "done", category: "Quant", loc: 397 },
  { id: 10, name: "Smart Alerts", description: "Price alerts, volume spikes, RSI thresholds, earnings date reminders with multi-channel delivery", status: "done", category: "Infrastructure", loc: 526 },
  { id: 11, name: "Patent Tracking", description: "USPTO patent filings, R&D velocity scoring, innovation index for any company", status: "done", category: "Alt Data", loc: 372 },
  { id: 12, name: "Job Posting Signals", description: "Hiring velocity as leading indicator, department growth analysis, geographic expansion tracking", status: "done", category: "Alt Data", loc: 410 },
  { id: 13, name: "Supply Chain Mapping", description: "SEC NLP for supplier/customer relationships, dependency graphs, concentration risk", status: "done", category: "Alt Data", loc: 451 },
  { id: 14, name: "Weather & Agriculture", description: "NOAA weather data, crop conditions, energy demand signals for ag/energy sectors", status: "done", category: "Alt Data", loc: 495 },
  { id: 15, name: "Bond Analytics", description: "Yield curves, credit spreads, duration, convexity analysis for fixed income", status: "done", category: "Fixed Income", loc: 439 },
  { id: 16, name: "SEC NLP Analysis", description: "Risk factor extraction, MD&A sentiment scoring, change detection across filings", status: "done", category: "Intelligence", loc: 505 },
  { id: 17, name: "IPO & SPAC Tracker", description: "Upcoming IPOs, SPAC arbitrage opportunities, lock-up expiry dates", status: "done", category: "Events", loc: 462 },
  { id: 18, name: "M&A Deal Flow", description: "Announced deals, merger arb spreads, completion probability scoring", status: "done", category: "Events", loc: 497 },
  { id: 19, name: "Activist Investor Tracking", description: "13D filings, campaign tracking, activist target identification", status: "done", category: "Alt Data", loc: 456 },
  { id: 20, name: "ESG Scoring", description: "Environmental, social, governance composite scores and peer comparison", status: "done", category: "Alt Data", loc: 430 },
  { id: 21, name: "Quant Factor Zoo", description: "Replicate 400+ published academic factors with statistical validation", status: "done", category: "Quant", loc: 1208 },
  { id: 22, name: "Market Microstructure", description: "Bid-ask spreads, order flow imbalance, liquidity scoring, market maker activity", status: "done", category: "Quant", loc: 492 },
  { id: 23, name: "AI Research Reports", description: "One-click LLM-generated equity research pulling from all data sources", status: "done", category: "Intelligence", loc: 409 },
  { id: 24, name: "Data Quality Monitor", description: "Automated staleness checks, source health validation, alert triggers for broken feeds", status: "done", category: "Infrastructure", loc: 380 },
  { id: 25, name: "Real-time Streaming", description: "WebSocket feeds for live prices via Polygon, Finnhub, Alpaca. Level 2 quotes", status: "done", category: "Infrastructure", loc: 332 },
  { id: 26, name: "ML Earnings Predictor", description: "Random Forest + XGBoost ensemble predicting earnings beats/misses with 77% accuracy", status: "done", category: "ML/AI", loc: 402 },
  { id: 27, name: "Correlation Heatmaps", description: "Cross-asset regime change detection across 22 ETFs with Z-score anomaly flagging", status: "done", category: "Quant", loc: 499 },
  { id: 28, name: "Options GEX Tracker", description: "Dealer gamma exposure positioning, pin risk at major strikes, hedging flow analysis", status: "done", category: "Derivatives", loc: 498 },
  { id: 29, name: "Hedge Fund 13F Replication", description: "Clone top fund positions, track quarterly changes, smart money flow analysis", status: "done", category: "Alt Data", loc: 681 },
  { id: 30, name: "CDS Spreads", description: "Sovereign and corporate credit risk signals from credit default swap markets", status: "done", category: "Fixed Income", loc: 486 },
  { id: 31, name: "Fama-French Regression", description: "Statistical factor attribution and multi-factor risk decomposition", status: "done", category: "Quant", loc: 390 },
  { id: 32, name: "Pairs Trading Signals", description: "Cointegration detection, mean reversion opportunities, spread monitoring", status: "done", category: "Quant", loc: 518 },
  { id: 33, name: "Sector Rotation Model", description: "Economic cycle indicators, relative strength rotation strategies", status: "done", category: "Quant", loc: 411 },
  { id: 34, name: "Monte Carlo Simulation", description: "Scenario analysis, probabilistic forecasting, tail risk modeling", status: "done", category: "Quant", loc: 518 },
  { id: 35, name: "Kalman Filter Trends", description: "Adaptive moving averages, regime change signals with state-space models", status: "done", category: "Quant", loc: 575 },
  { id: 36, name: "Black-Litterman Allocation", description: "Combine market equilibrium with investor views for portfolio construction", status: "done", category: "Quant", loc: 481 },
  { id: 37, name: "Walk-Forward Optimization", description: "Out-of-sample strategy tuning with rolling windows to prevent overfitting", status: "done", category: "Quant", loc: 421 },
  { id: 38, name: "Multi-Timeframe Analysis", description: "Combine signals from daily/weekly/monthly charts for confirmation", status: "done", category: "Quant", loc: 476 },
  { id: 39, name: "Order Book Depth", description: "Level 2 data analysis, bid-ask imbalance, hidden liquidity detection", status: "done", category: "Quant", loc: 452 },
  { id: 40, name: "Smart Alert Delivery", description: "Multi-channel notifications (email, SMS, Discord, Telegram) with rate limiting", status: "done", category: "Infrastructure", loc: 619 },
  { id: 41, name: "Alert Backtesting", description: "Test alert strategies historically, measure signal quality, false positive rates", status: "done", category: "Infrastructure", loc: 550 },
  { id: 42, name: "Custom Alert DSL", description: "Domain-specific language for complex multi-condition alert rules", status: "done", category: "Infrastructure", loc: 658 },
  { id: 43, name: "Crypto On-Chain Analytics", description: "Whale wallet tracking, token flows, DEX volume, gas fee analysis", status: "done", category: "Multi-Asset", loc: 565 },
  { id: 44, name: "Commodity Futures Curves", description: "Contango/backwardation signals, roll yields, term structure analysis", status: "done", category: "Multi-Asset", loc: 440 },
  { id: 45, name: "Fed Policy Prediction", description: "FOMC analysis, dot plot tracking, rate hike probability scoring", status: "done", category: "ML/AI", loc: 512 },
  { id: 46, name: "Satellite Imagery Proxies", description: "Parking lot occupancy, shipping containers, construction activity tracking via Google Trends, FRED, Baltic Dry Index", status: "done", category: "Alt Data", loc: 457 },
  { id: 47, name: "Earnings Call NLP", description: "Tone analysis, linguistic markers, management confidence, question-dodging detection", status: "done", category: "Intelligence", loc: 1208 },

  // ============ BUILDING (48-52) ============
  { id: 48, name: "Peer Network Analysis", description: "Interconnected company relationships, revenue dependency mapping, systemic risk", status: "done", category: "Intelligence", loc: 387 },
  { id: 49, name: "Political Risk Scoring", description: "Geopolitical events via GDELT, OFAC sanctions tracking, regulatory change impact modeling", status: "done", category: "Alt Data", loc: 421 },
  { id: 50, name: "Product Launch Tracker", description: "Social buzz via Google Trends, pre-order velocity, review sentiment for new product launches", status: "done", category: "Alt Data", loc: 443 },
  { id: 51, name: "Executive Compensation", description: "SEC DEF 14A proxy filings, pay-for-performance correlation, peer comparison", status: "done", category: "Alt Data", loc: 398 },
  { id: 52, name: "Revenue Quality Analysis", description: "Cash flow vs earnings divergence, DSO trends, channel stuffing detection via SEC XBRL", status: "done", category: "Intelligence", loc: 405 },
  { id: 53, name: "Peer Earnings Comparison", description: "Beat/miss patterns, guidance trends, analyst estimate dispersion", status: "done", category: "Events", loc: 447 },

  // ============ PLANNED: Original (54-93) ============
  { id: 54, name: "Crypto Correlation Indicators", description: "BTC dominance, altcoin seasonality, DeFi TVL impact on tech stocks", status: "done", category: "Multi-Asset", loc: 443 },
  { id: 55, name: "Tax Loss Harvesting", description: "Identify opportunities, track wash sale rules, estimate tax savings", status: "done", category: "Quant", loc: 485 },
  { id: 56, name: "Share Buyback Analysis", description: "Authorization vs execution, dilution impact, return on buyback calculation", status: "done", category: "Events", loc: 495 },
  { id: 57, name: "Dividend Sustainability", description: "Payout ratio trends, FCF coverage, dividend cut probability modeling", status: "done", category: "Events", loc: 552 },
  { id: 58, name: "Institutional Ownership", description: "13F changes, whale accumulation/distribution, smart money flow patterns", status: "done", category: "Alt Data", loc: 583 },
  { id: 59, name: "Earnings Quality Metrics", description: "Accruals ratio, Beneish M-Score, Altman Z-Score for fraud/distress detection", status: "done", category: "Intelligence", loc: 575 },
  { id: 60, name: "Sector Performance Attribution", description: "Decompose returns into sector allocation vs stock selection effects", status: "done", category: "Quant", loc: 320 },
  { id: 61, name: "Dark Pool Tracker", description: "FINRA ADF block trade detection, institutional accumulation patterns", status: "done", category: "Alt Data", loc: 645 },
  { id: 62, name: "Estimate Revision Tracker", description: "Analyst upgrades/downgrades velocity, estimate momentum indicators", status: "done", category: "Events", loc: 456 },
  { id: 63, name: "Corporate Action Calendar", description: "Dividend ex-dates, splits, spin-offs, rights offerings with impact analysis", status: "done", category: "Events", loc: 612 },
  { id: 64, name: "Convertible Bond Arbitrage", description: "Conversion premium analysis, implied volatility, delta hedging opportunities", status: "done", category: "Fixed Income", loc: 730 },
  { id: 65, name: "Short Squeeze Detector", description: "High short interest + low float + technical squeeze signals via FINRA", status: "done", category: "Alt Data", loc: 796 },
  { id: 66, name: "Market Regime Detection", description: "Volatility clustering, correlation breakdowns, risk-on vs risk-off identification", status: "done", category: "Quant", loc: 540 },
  { id: 67, name: "Activist Success Predictor", description: "ML model trained on historical activist campaign outcomes and governance scores", status: "done", category: "ML/AI", loc: 517 },
  { id: 68, name: "13D/13G Filing Alerts", description: "Real-time SEC EDGAR RSS notifications for new activist filings and stake changes", status: "done", category: "Events", loc: 438 },
  { id: 69, name: "Proxy Fight Tracker", description: "ISS/Glass Lewis recommendations, shareholder voting, proxy contest outcomes", status: "done", category: "Events", loc: 608 },
  { id: 70, name: "Greenwashing Detection", description: "NLP analysis of ESG reports vs actual metrics, identify inconsistencies", status: "done", category: "Intelligence", loc: 597 },
  { id: 71, name: "Sustainability-Linked Bonds", description: "Monitor SLB issuance, KPI achievement, coupon step-up triggers", status: "done", category: "Fixed Income", loc: 503 },
  { id: 72, name: "Climate Risk Scoring", description: "NASA/NOAA physical risk, EPA transition risk, carbon pricing scenario analysis", status: "done", category: "Alt Data", loc: 365 },
  { id: 73, name: "Factor Timing Model", description: "Regime detection for when factors work, adaptive factor rotation", status: "done", category: "ML/AI", loc: 505 },
  { id: 74, name: "ML Factor Discovery", description: "Automated discovery of new predictive factors with feature engineering", status: "done", category: "ML/AI", loc: 683 },
  { id: 75, name: "Transaction Cost Analysis", description: "Market impact estimation, bid-ask modeling, execution optimization for large trades", status: "done", category: "Quant", loc: 610 },
  { id: 76, name: "AI Earnings Call Analyzer", description: "Real-time tone detection, hesitation patterns, executive confidence scoring via LLM", status: "done", category: "ML/AI", loc: 797 },
  { id: 77, name: "Cross-Exchange Arbitrage", description: "Price discrepancies across NYSE/NASDAQ/IEX/CBOE with execution optimization", status: "done", category: "Quant", loc: 400 },
  { id: 78, name: "Regulatory Event Calendar", description: "FOMC, CPI, GDP, NFP tracking with market reaction backtests and volatility forecasts", status: "done", category: "Events", loc: 682 },
  { id: 79, name: "PDF Report Exporter", description: "Convert markdown reports to professional PDF with charts and email delivery", status: "done", category: "Infrastructure", loc: 485 },
  { id: 80, name: "Alert Backtesting Dashboard", description: "Visualize historical alert performance with profit factor and Sharpe ratio", status: "done", category: "Infrastructure", loc: 520 },
  { id: 81, name: "Portfolio Construction Tool", description: "MPT optimizer, Black-Litterman, ESG constraints, tax-aware rebalancing", status: "done", category: "Quant", loc: 862 },
  { id: 82, name: "Live Earnings Transcription", description: "Stream earnings calls, transcribe with Whisper, extract signals in real-time", status: "done", category: "ML/AI", loc: 536 },
  { id: 83, name: "Smart Data Prefetching", description: "ML predicts which data will be requested next, preloads during idle", status: "done", category: "Infrastructure", loc: 456 },
  { id: 84, name: "Multi-Source Reconciliation", description: "Compare data across sources, flag discrepancies, confidence-based voting", status: "done", category: "Infrastructure", loc: 634 },
  { id: 85, name: "Neural Price Prediction", description: "LSTM/Transformer models for multi-horizon forecasting with uncertainty quantification", status: "done", category: "ML/AI", loc: 597 },
  { id: 86, name: "Order Book Imbalance", description: "Level 3 data, predict short-term price movements from bid/ask imbalances", status: "done", category: "Quant", loc: 535 },
  { id: 87, name: "Correlation Anomaly Detector", description: "Identify unusual correlation breakdowns, detect regime shifts, flag arbitrage", status: "done", category: "ML/AI", loc: 363 },
  { id: 88, name: "Deep Learning Sentiment", description: "FinBERT for earnings calls, SEC filings, news with entity-level sentiment", status: "done", category: "ML/AI", loc: 598 },
  { id: 89, name: "Volatility Surface Modeling", description: "IV smile/skew analysis, volatility arbitrage, straddle/strangle scanner", status: "done", category: "Derivatives", loc: 461 },
  { id: 90, name: "ML Stock Screening", description: "Multi-factor ML ranking with walk-forward validation and auto-rebalancing", status: "done", category: "ML/AI", loc: 405 },
  { id: 91, name: "Insider Trading Network", description: "Map SEC Form 4 insider relationships, detect coordinated buying/selling clusters", status: "done", category: "Alt Data", loc: 739 },
  { id: 92, name: "Earnings Quality Forensics", description: "Deep accounting red flag detection with Beneish M-Score and fraud probability", status: "done", category: "Intelligence" , loc: 576 },
  { id: 93, name: "Social Sentiment Spike Detector", description: "Real-time Reddit/Twitter surge detection, meme stock momentum, pump detection", status: "done", category: "ML/AI", loc: 716 },

  // ============ GLOBAL MACRO & GOVERNMENT DATA (94-133) — Bloomberg WECO/ECO Killer ============
  { id: 94, name: "World Bank Open Data", description: "GDP, GNI, inflation, FDI, poverty for 217 countries via api.worldbank.org. Weekly refresh.", status: "done", category: "Global Macro", loc: 656 },
  { id: 95, name: "IMF World Economic Outlook", description: "GDP/CPI forecasts for 190 countries via IMF DataMapper API. Updated Apr & Oct.", status: "done", category: "Global Macro", loc: 537 },
  { id: 96, name: "CIA World Factbook", description: "Demographics, military spend, resources, trade partners for 266 countries. Monthly scrape.", status: "done", category: "Global Macro", loc: 681 },
  { id: 97, name: "US BLS Employment & Prices", description: "CPI components, PPI, NFP, wages, productivity via api.bls.gov. Monthly on release day.", status: "done", category: "Global Macro", loc: 632 },
  { id: 98, name: "US Census Economic Indicators", description: "Retail sales, housing starts, building permits, trade deficit via api.census.gov. Monthly.", status: "done", category: "Global Macro", loc: 663 },
  { id: 99, name: "Eurostat EU Statistics", description: "EU-27 GDP, HICP inflation, unemployment, industrial production via SDMX API. Weekly.", status: "done", category: "Global Macro", loc: 668 },
  { id: 100, name: "Bank of Japan Statistics", description: "Tankan survey, monetary base, FX reserves, interest rates. Monthly.", status: "done", category: "Global Macro", loc: 482 },
  { id: 101, name: "China NBS/PBOC Data", description: "China PMI, trade surplus, property prices, credit growth, FX reserves. Monthly scrape.", status: "done", category: "Global Macro", loc: 660 },
  { id: 102, name: "OECD Leading Indicators", description: "CLI composite indicators, productivity, housing prices for 38 OECD countries. Monthly.", status: "done", category: "Global Macro", loc: 610 },
  { id: 103, name: "UN Comtrade Trade Flows", description: "Bilateral trade flows, commodity imports/exports for 200+ countries. Monthly.", status: "done", category: "Global Macro", loc: 834 },
  { id: 104, name: "FRED Enhanced (300+ Series)", description: "Yield curve, M2, financial conditions, LEI, consumer credit via FRED API. Daily-monthly.", status: "done", category: "Global Macro", loc: 804 },
  { id: 105, name: "ECB Statistical Warehouse", description: "Euro rates, M1/M2/M3, bank lending, TARGET balances via SDMX. Weekly.", status: "done", category: "Global Macro", loc: 608 },
  { id: 106, name: "Global PMI Aggregator", description: "Manufacturing & Services PMI for 30+ countries from ISM/S&P Global. Monthly.", status: "done", category: "Global Macro", loc: 853 },
  { id: 107, name: "Global Government Bond Yields", description: "10Y yields for 40+ countries, real yields, breakeven inflation. Daily.", status: "done", category: "Global Macro", loc: 536 },
  { id: 108, name: "Sovereign Wealth Fund Tracker", description: "SWF AUM, allocation changes, major investments for $12T+ in assets. Quarterly.", status: "done", category: "Global Macro", loc: 917 },
  { id: 109, name: "Central Bank Balance Sheets", description: "Fed/ECB/BOJ/PBOC total assets, QE holdings, reserves. Weekly (Fed H.4.1).", status: "done", category: "Global Macro", loc: 582 },
  { id: 110, name: "Global Shipping Indicators", description: "Baltic Dry Index, container freight rates, port congestion. Daily.", status: "done", category: "Global Macro", loc: 605 },
  { id: 111, name: "Global Real Estate Indices", description: "Home prices for 60+ countries, rent indices, affordability via FRED/BIS. Monthly.", status: "done", category: "Global Macro", loc: 808 },
  { id: 112, name: "EIA Energy Data", description: "Crude oil/nat gas inventories, SPR, refinery utilization via api.eia.gov. Weekly.", status: "done", category: "Global Macro", loc: 564 },
  { id: 113, name: "Global Debt Monitor", description: "Govt debt/GDP, corporate debt, credit gaps for 60+ countries via BIS/IMF. Quarterly.", status: "done", category: "Global Macro", loc: 711 },
  { id: 114, name: "USDA Crop & Agriculture Data", description: "WASDE, crop production, livestock, farm prices via USDA NASS API. Monthly.", status: "done", category: "Global Macro", loc: 699 },
  { id: 115, name: "WTO Tariff & Trade Disputes", description: "Tariff rates, anti-dumping duties, trade dispute tracker via data.wto.org. Monthly.", status: "done", category: "Global Macro", loc: 691 },
  { id: 116, name: "ILO Global Labor Statistics", description: "Employment, wages, inequality for 180+ countries via ILOSTAT. Quarterly.", status: "done", category: "Global Macro", loc: 771 },
  { id: 117, name: "BIS Global Banking Statistics", description: "Cross-border banking, derivatives turnover, FX volumes. Quarterly.", status: "done", category: "Global Macro", loc: 886 },
  { id: 118, name: "US Treasury Auctions & Debt", description: "Auction results, bid-to-cover, TIC foreign holdings via treasurydirect.gov. Weekly.", status: "done", category: "Global Macro", loc: 476 },
  { id: 119, name: "Reserve Bank of India Stats", description: "India GDP, WPI, CPI, FX reserves, repo rate from RBI. Monthly.", status: "done", category: "Country Stats", loc: 730 },
  { id: 120, name: "Brazil BCB Economic Data", description: "SELIC rate, IPCA inflation, GDP, trade balance via BCB API. Monthly.", status: "done", category: "Country Stats", loc: 509 },
  { id: 121, name: "Australian Bureau of Statistics", description: "Australia GDP, CPI, employment, housing via ABS + RBA. Monthly.", status: "done", category: "Country Stats", loc: 588 },
  { id: 122, name: "Korean Statistical Information", description: "Korea GDP, CPI, semiconductor exports via KOSIS + BOK. Monthly.", status: "done", category: "Country Stats", loc: 707 },
  { id: 123, name: "Mexican INEGI Statistics", description: "Mexico GDP, CPI, employment, remittances via INEGI API. Monthly.", status: "done", category: "Country Stats", loc: 456 },
  { id: 124, name: "Turkish Statistical Institute", description: "Turkey CPI/PPI, GDP, trade, unemployment via TUIK API. Monthly.", status: "done", category: "Country Stats", loc: 810 },
  { id: 125, name: "South Africa Reserve Bank", description: "SA GDP, CPI, repo rate, rand, mining output. Monthly.", status: "done", category: "Country Stats", loc: 736 },
  { id: 126, name: "Saudi Arabia GASTAT", description: "Saudi GDP, CPI, oil revenue, non-oil GDP diversification. Quarterly.", status: "done", category: "Country Stats", loc: 852 },
  { id: 127, name: "Israel CBS Statistics", description: "Israel GDP, CPI, housing prices, tech exports via CBS. Monthly.", status: "done", category: "Country Stats", loc: 489 },
  { id: 128, name: "Nigeria NBS Statistics", description: "Nigeria GDP, CPI, oil production, trade balance. Quarterly.", status: "done", category: "Country Stats", loc: 587 },
  { id: 129, name: "Argentina INDEC Statistics", description: "Argentina CPI, GDP, trade, poverty rate via INDEC. Monthly.", status: "done", category: "Country Stats", loc: 550 },
  { id: 130, name: "Singapore DOS/MAS Statistics", description: "Singapore GDP, CPI, trade, MAS monetary policy via SingStat API. Monthly.", status: "done", category: "Country Stats", loc: 655 },
  { id: 131, name: "Switzerland SNB Data", description: "Swiss GDP, CPI, SNB FX reserves, sight deposits via data.snb.ch. Monthly.", status: "done", category: "Country Stats", loc: 538 },
  { id: 132, name: "Poland GUS Statistics", description: "Poland GDP, CPI, employment, industrial output via BDL API. Monthly.", status: "done", category: "Country Stats", loc: 711 },
  { id: 133, name: "Global Inflation Tracker", description: "100+ countries CPI comparison, real interest rates, aggregated from all central banks. Monthly.", status: "done", category: "Global Macro", loc: 695 },

  // ============ EQUITY ANALYSIS (134-153) — Bloomberg FA/EQS Killer ============
  { id: 134, name: "SEC XBRL Financial Statements", description: "Machine-readable financials for every US public company via SEC XBRL API. Quarterly.", status: "done", category: "Equity", loc: 605 },
  { id: 135, name: "Global Stock Exchange Holidays", description: "Trading calendar for all major exchanges worldwide. Annual update.", status: "done", category: "Equity", loc: 923 },
  { id: 136, name: "Index Reconstitution Tracker", description: "S&P 500, Russell, MSCI add/delete tracking from press releases. Quarterly.", status: "done", category: "Equity", loc: 519 },
  { id: 137, name: "Insider Transaction Heatmap", description: "SEC Form 4 cluster analysis, sector-wide insider buying/selling patterns. Daily.", status: "done", category: "Equity", loc: 674 },
  { id: 138, name: "Share Float & Ownership Structure", description: "Float shares, insider %, institutional % from SEC filings + Yahoo. Quarterly.", status: "done", category: "Equity", loc: 550 },
  { id: 139, name: "Dividend History & Projections", description: "Complete dividend history, growth rates, ex-date calendar. Daily.", status: "done", category: "Equity", loc: 683 },
  { id: 140, name: "Equity Screener (Multi-Factor)", description: "Screen 8000+ stocks on 50+ fundamental/technical factors via Yahoo + SEC. Daily.", status: "done", category: "Equity", loc: 610 },
  { id: 141, name: "Comparable Company Analysis", description: "Auto-generate comps tables with EV/EBITDA, P/E, margins for any sector. Quarterly.", status: "done", category: "Equity", loc: 536 },
  { id: 142, name: "DCF Valuation Engine", description: "Automated discounted cash flow models from SEC XBRL financials + FRED rates. Quarterly.", status: "done", category: "Equity", loc: 664 },
  { id: 143, name: "Relative Valuation Matrix", description: "Cross-sector valuation comparison heatmaps. Daily.", status: "done", category: "Equity", loc: 419 },
  { id: 144, name: "Earnings Surprise History", description: "Historical beat/miss patterns, whisper numbers, post-earnings drift. Quarterly.", status: "done", category: "Equity", loc: 820 },
  { id: 145, name: "Analyst Target Price Tracker", description: "Consensus targets, bull/bear cases, revision velocity from Yahoo Finance. Daily.", status: "done", category: "Equity", loc: 630 },
  { id: 146, name: "Stock Split & Corporate Events", description: "Split history, corporate action impact analysis from SEC/Yahoo. Daily.", status: "done", category: "Equity", loc: 754 },
  { id: 147, name: "ADR/GDR Arbitrage Monitor", description: "Dual-listed price discrepancies, FX-adjusted spreads. Daily.", status: "done", category: "Equity", loc: 535 },
  { id: 148, name: "SPAC Lifecycle Tracker", description: "SPAC trust values, deal timelines, redemption rates from SEC S-1/8-K. Daily.", status: "done", category: "Equity", loc: 519 },
  { id: 149, name: "Secondary Offering Monitor", description: "Follow-on offerings, shelf registrations from SEC S-3/424B filings. Daily.", status: "done", category: "Equity", loc: 633 },
  { id: 150, name: "Stock Loan & Borrow Costs", description: "Short borrow rates, hard-to-borrow lists from FINRA Reg SHO. Daily.", status: "done", category: "Equity", loc: 584 },
  { id: 151, name: "ETF Flow Tracker", description: "ETF creation/redemption, flow data from SEC N-PORT + etfdb.com. Daily.", status: "done", category: "Equity", loc: 580 },
  { id: 152, name: "Mutual Fund Flow Analysis", description: "Fund flows, holdings changes from SEC N-PORT filings. Monthly.", status: "done", category: "Equity", loc: 530 },
  { id: 153, name: "Global Equity Index Returns", description: "Daily returns for 50+ global indices (S&P, FTSE, DAX, Nikkei, etc). Daily.", status: "done", category: "Equity", loc: 769 },

  // ============ FIXED INCOME (154-168) — Bloomberg FI Killer ============
  { id: 154, name: "Treasury Yield Curve (Full)", description: "Daily US Treasury curve from 1M to 30Y via treasury.gov. Daily.", status: "done", category: "Fixed Income", loc: 627 },
  { id: 155, name: "Municipal Bond Monitor", description: "Muni bond trades, yields, credit events from EMMA (emma.msrb.org). Daily.", status: "done", category: "Fixed Income", loc: 751 },
  { id: 156, name: "Corporate Bond Spreads", description: "IG/HY OAS from FRED (ICE BofA indices), sector spreads. Daily.", status: "done", category: "Fixed Income", loc: 599 },
  { id: 157, name: "High Yield Bond Tracker", description: "HY spreads, distressed debt, default rates from FRED. Daily.", status: "done", category: "Fixed Income", loc: 391 },
  { id: 158, name: "EM Sovereign Spread Monitor", description: "Emerging market bond spreads (EMBI) from FRED + JPMorgan. Daily.", status: "done", category: "Fixed Income", loc: 356 },
  { id: 159, name: "TIPS & Breakeven Inflation", description: "Real yields, breakeven rates, inflation expectations from FRED. Daily.", status: "done", category: "Fixed Income", loc: 762 },
  { id: 160, name: "Swap Rate Curves", description: "Interest rate swap curves from FRED + ECB. Daily.", status: "done", category: "Fixed Income", loc: 529 },
  { id: 161, name: "Repo Rate Monitor", description: "SOFR, repo rates, reverse repo from NY Fed. Daily.", status: "done", category: "Fixed Income", loc: 557 },
  { id: 162, name: "Commercial Paper Rates", description: "AA Financial/Nonfinancial CP rates from FRED. Daily.", status: "done", category: "Fixed Income", loc: 460 },
  { id: 163, name: "CLO/ABS Market Monitor", description: "Structured credit from FRED + SEC N-PORT. Monthly.", status: "done", category: "Fixed Income", loc: 739 },
  { id: 164, name: "Sovereign Rating Tracker", description: "S&P/Moody's/Fitch rating changes from press releases. On change.", status: "done", category: "Fixed Income", loc: 534 },
  { id: 165, name: "Bond New Issue Calendar", description: "Upcoming corporate/sovereign issuance from SEC + exchanges. Daily.", status: "done", category: "Fixed Income", loc: 552 },
  { id: 166, name: "Central Bank Rate Decisions", description: "Rate decisions for 40+ central banks worldwide. On decision.", status: "done", category: "Fixed Income", loc: 843 },
  { id: 167, name: "Inflation-Linked Bond Tracker", description: "Global linkers from FRED + ECB + BOE. Daily.", status: "done", category: "Fixed Income", loc: 976 },
  { id: 168, name: "Money Market Fund Flows", description: "MMF AUM and flows from SEC N-MFP filings. Monthly.", status: "done", category: "Fixed Income", loc: 732 },

  // ============ COMMODITIES (169-180) — Bloomberg CMDX Killer ============
  { id: 169, name: "Crude Oil Fundamentals", description: "EIA inventories + OPEC MOMR production data. Weekly/Monthly.", status: "done", category: "Commodities", loc: 710 },
  { id: 170, name: "Natural Gas Supply/Demand", description: "EIA weekly storage, production, demand via api.eia.gov. Weekly.", status: "done", category: "Commodities", loc: 469 },
  { id: 171, name: "Gold & Precious Metals", description: "World Gold Council data, LBMA prices, ETF holdings. Daily.", status: "done", category: "Commodities", loc: 444 },
  { id: 172, name: "Industrial Metals", description: "LME copper, aluminum, zinc, nickel prices and inventories. Daily.", status: "done", category: "Commodities", loc: 523 },
  { id: 173, name: "Agricultural Commodities", description: "USDA WASDE, CBOT grains/softs via Yahoo Finance. Monthly.", status: "done", category: "Commodities", loc: 672 },
  { id: 174, name: "Livestock & Meat Markets", description: "USDA AMS daily livestock reports, cattle/hog prices. Daily.", status: "done", category: "Commodities", loc: 674 },
  { id: 175, name: "OPEC Production Monitor", description: "OPEC monthly oil market report, production quotas vs actual. Monthly.", status: "done", category: "Commodities", loc: 561 },
  { id: 176, name: "LNG & Gas Market Tracker", description: "Global LNG prices, trade flows, terminal utilization. Weekly.", status: "done", category: "Commodities", loc: 533 },
  { id: 177, name: "Carbon Credits & Emissions", description: "EU ETS prices, global carbon market data from ICAP. Daily.", status: "done", category: "Commodities", loc: 630 },
  { id: 178, name: "Rare Earths & Strategic Minerals", description: "USGS mineral commodity summaries, supply chain risk. Monthly.", status: "done", category: "Commodities", loc: 592 },
  { id: 179, name: "Freight & Shipping Rates", description: "Baltic Dry Index, container rates from Freightos/Drewry. Daily.", status: "done", category: "Commodities", loc: 605 },
  { id: 180, name: "CFTC COT Reports", description: "Commitments of Traders — speculative/commercial positioning. Weekly.", status: "done", category: "Commodities", loc: 449 },

  // ============ FX & CRYPTO (181-190) — Bloomberg FXGO Killer ============
  { id: 181, name: "Global FX Rates (150+ pairs)", description: "ECB + FRED + exchangerate.host for 150+ currency pairs. Daily.", status: "done", category: "FX & Crypto", loc: 867 },
  { id: 182, name: "FX Carry Trade Monitor", description: "Interest rate differentials, carry returns, risk-adjusted carry. Daily.", status: "done", category: "FX & Crypto", loc: 467 },
  { id: 183, name: "FX Volatility Surface", description: "Implied vol for major pairs, risk reversals, butterfly spreads. Daily.", status: "done", category: "FX & Crypto", loc: 474 },
  { id: 184, name: "EM Currency Crisis Monitor", description: "FX reserves, current account, real effective exchange rates from FRED/BIS. Daily.", status: "done", category: "FX & Crypto", loc: 556 },
  { id: 185, name: "Crypto Exchange Flow Monitor", description: "Exchange inflows/outflows, whale movements via CoinGecko + Glassnode. Hourly.", status: "done", category: "FX & Crypto", loc: 432 },
  { id: 186, name: "DeFi TVL & Yield Aggregator", description: "Total value locked, yield farming rates via DeFi Llama API. Hourly.", status: "done", category: "FX & Crypto", loc: 578 },
  { id: 187, name: "Stablecoin Supply Monitor", description: "USDT/USDC/DAI supply, mint/burn events via DeFi Llama. Daily.", status: "done", category: "FX & Crypto", loc: 367 },
  { id: 188, name: "Crypto Derivatives (Futures Basis)", description: "Perpetual funding rates, futures basis, open interest. Hourly.", status: "done", category: "FX & Crypto", loc: 580 },
  { id: 189, name: "NFT Market Tracker", description: "Collection floor prices, volume, wash trading detection via OpenSea. Daily.", status: "done", category: "FX & Crypto", loc: 527 },
  { id: 190, name: "Cross-Chain Bridge Monitor", description: "Bridge TVL, flow direction, exploit risk scoring via DeFi Llama. Daily.", status: "done", category: "FX & Crypto", loc: 453 },

  // ============ ALTERNATIVE DATA (191-200) — Bloomberg BNEF+ Killer ============
  { id: 191, name: "Global Electricity Demand", description: "ENTSO-E (Europe), EIA (US), CAISO grid demand as industrial proxy. Daily.", status: "done", category: "Alt Data", loc: 579 },
  { id: 192, name: "Airport Traffic & Aviation", description: "Eurocontrol, FAA flight data, airline capacity as economic proxy. Monthly.", status: "done", category: "Alt Data", loc: 455 },
  { id: 193, name: "Container Port Throughput", description: "Shanghai, Rotterdam, LA/Long Beach TEU volumes. Monthly.", status: "done", category: "Alt Data", loc: 493 },
  { id: 194, name: "Global Tourism Statistics", description: "UNWTO arrivals, hotel occupancy, airline passenger data. Quarterly.", status: "done", category: "Alt Data", loc: 598 },
  { id: 195, name: "Semiconductor Chip Data", description: "SIA monthly sales, WSTS forecasts, fab utilization. Monthly.", status: "done", category: "Alt Data", loc: 506 },
  { id: 196, name: "Auto Sales & EV Registrations", description: "BEA auto sales, ACEA (EU), EV-volumes.com registrations. Monthly.", status: "done", category: "Alt Data", loc: 498 },
  { id: 197, name: "Bankruptcy & Default Tracker", description: "PACER Chapter 11 filings, SEC 8-K bankruptcy notices. Daily.", status: "done", category: "Alt Data", loc: 371 },
  { id: 198, name: "Private Equity & VC Deal Flow", description: "Crunchbase free tier + SEC Form D filings. Weekly.", status: "done", category: "Alt Data", loc: 608 },
  { id: 199, name: "Global Health Impact Monitor", description: "WHO disease outbreaks, pandemic economic impact data. Weekly.", status: "done", category: "Alt Data", loc: 556 },
  { id: 200, name: "Academic Finance Paper Tracker", description: "SSRN, arXiv q-fin, NBER working papers — new alpha signals. Weekly.", status: "done", category: "Alt Data", loc: 790 },
];

export const dataSources = [
  // Active (used by completed modules)
  { name: "Yahoo Finance", icon: "📈", type: "Market Data", desc: "Real-time & historical prices, options, fundamentals", status: "active", modules: ["prices", "options", "technicals", "dividends", "earnings", "company_profile", "screener"] },
  { name: "SEC EDGAR", icon: "📑", type: "Regulatory", desc: "10-K, 10-Q, 8-K, DEF 14A, 13D/F filings, XBRL", status: "active", modules: ["sec_edgar", "sec_nlp", "earnings_transcripts", "activist_investor_tracking", "exec_comp", "revenue_quality"] },
  { name: "CoinGecko", icon: "₿", type: "Crypto", desc: "Cryptocurrency prices, market cap, volume, on-chain", status: "active", modules: ["crypto", "crypto_onchain"] },
  { name: "Google News RSS", icon: "📰", type: "News", desc: "Real-time news aggregation with NLP sentiment", status: "active", modules: ["news_sentiment"] },
  { name: "FRED (Federal Reserve)", icon: "🏦", type: "Macro", desc: "GDP, CPI, rates, yield curves, financial conditions — 800K+ series", status: "active", modules: ["macro", "fred_enhanced", "bond_analytics", "real_estate"] },
  { name: "USPTO", icon: "💡", type: "Alt Data", desc: "Patent filings, R&D velocity", status: "active", modules: ["patent_tracking"] },
  { name: "NOAA", icon: "🌾", type: "Alt Data", desc: "Weather data, crop conditions, energy demand", status: "active", modules: ["weather_agriculture"] },
  { name: "Reddit/StockTwits", icon: "💬", type: "Social", desc: "Social sentiment, retail investor attention", status: "active", modules: ["social_sentiment"] },
  { name: "Congressional Disclosures", icon: "🏛️", type: "Alt Data", desc: "Politician trading disclosures", status: "active", modules: ["congress_trades"] },
  { name: "Polygon.io", icon: "📡", type: "Streaming", desc: "Real-time WebSocket price feeds", status: "active", modules: ["streaming"] },
  { name: "Finnhub", icon: "📡", type: "Streaming", desc: "Multi-market streaming data", status: "active", modules: ["streaming"] },
  { name: "Alpaca", icon: "📡", type: "Streaming", desc: "Commission-free trading data feeds", status: "active", modules: ["streaming"] },
  { name: "X.ai (Grok)", icon: "🤖", type: "AI/LLM", desc: "Research report synthesis, earnings analysis", status: "active", modules: ["research_reports"] },
  { name: "DeFi Llama", icon: "🦙", type: "DeFi", desc: "DEX volume, TVL, protocol data", status: "active", modules: ["crypto_onchain", "defi_tvl"] },
  { name: "Etherscan", icon: "⛓️", type: "Blockchain", desc: "Ethereum transactions, gas fees, token transfers", status: "active", modules: ["crypto_onchain"] },
  { name: "GDELT Project", icon: "🌐", type: "Geopolitical", desc: "Global event database, political risk", status: "active", modules: ["political_risk"] },
  { name: "Ken French Data Library", icon: "📊", type: "Academic", desc: "Fama-French factors, academic research data", status: "active", modules: ["fama_french", "factor_zoo"] },
  { name: "Google Trends", icon: "🔍", type: "Alt Data", desc: "Search interest as demand proxy", status: "active", modules: ["product_launch", "satellite_proxies"] },
  // Planned (for phases 94-200)
  { name: "World Bank", icon: "🌍", type: "Macro", desc: "1,400+ indicators for 217 countries", status: "planned", modules: ["worldbank"] },
  { name: "IMF", icon: "🏦", type: "Macro", desc: "WEO forecasts, fiscal data for 190 countries", status: "planned", modules: ["imf_weo"] },
  { name: "CIA Factbook", icon: "🕵️", type: "Geopolitical", desc: "Country profiles, military, demographics", status: "planned", modules: ["cia_factbook"] },
  { name: "BLS", icon: "📊", type: "US Macro", desc: "CPI, employment, wages, productivity", status: "planned", modules: ["bls"] },
  { name: "US Census", icon: "🏠", type: "US Macro", desc: "Retail, housing, trade statistics", status: "planned", modules: ["census"] },
  { name: "Eurostat", icon: "🇪🇺", type: "EU Macro", desc: "EU-27 economic statistics", status: "planned", modules: ["eurostat"] },
  { name: "ECB", icon: "💶", type: "EU Macro", desc: "Euro rates, monetary aggregates, bank lending", status: "planned", modules: ["ecb"] },
  { name: "BOJ", icon: "🇯🇵", type: "Japan", desc: "Tankan, monetary policy, FX reserves", status: "planned", modules: ["boj"] },
  { name: "PBOC/NBS", icon: "🇨🇳", type: "China", desc: "PMI, credit, property, trade data", status: "planned", modules: ["china_nbs"] },
  { name: "OECD", icon: "📈", type: "Macro", desc: "Leading indicators for 38 countries", status: "planned", modules: ["oecd"] },
  { name: "UN Comtrade", icon: "🚢", type: "Trade", desc: "Global bilateral trade flows", status: "planned", modules: ["comtrade"] },
  { name: "BIS", icon: "🏦", type: "Macro", desc: "Global banking, derivatives, FX stats", status: "planned", modules: ["bis"] },
  { name: "Treasury Direct", icon: "🇺🇸", type: "Fixed Income", desc: "Auction results, foreign holdings", status: "active", modules: ["treasury_auctions"] },
  { name: "EIA", icon: "⛽", type: "Energy", desc: "Oil/gas inventories, production, renewables", status: "planned", modules: ["eia"] },
  { name: "USDA", icon: "🌽", type: "Agriculture", desc: "WASDE, crop production, livestock", status: "planned", modules: ["usda"] },
  { name: "CFTC", icon: "📋", type: "Positioning", desc: "Commitments of Traders reports", status: "planned", modules: ["cot"] },
  { name: "WTO", icon: "🌐", type: "Trade", desc: "Tariffs, trade disputes, anti-dumping", status: "planned", modules: ["wto"] },
  { name: "ILO", icon: "👷", type: "Labor", desc: "Global employment, wages for 180+ countries", status: "planned", modules: ["ilo"] },
  { name: "OPEC", icon: "🛢️", type: "Energy", desc: "Monthly oil market report, production data", status: "planned", modules: ["opec"] },
  { name: "USGS", icon: "⛏️", type: "Minerals", desc: "Rare earths, strategic mineral supply", status: "planned", modules: ["rare_earths"] },
  { name: "ENTSO-E", icon: "⚡", type: "Alt Data", desc: "European electricity grid data", status: "planned", modules: ["electricity"] },
  { name: "EMMA/MSRB", icon: "🏛️", type: "Fixed Income", desc: "Municipal bond trades and data", status: "planned", modules: ["muni_bonds"] },
  { name: "NY Fed", icon: "🏦", type: "Fixed Income", desc: "SOFR, repo rates, Treasury operations", status: "planned", modules: ["repo_rates"] },
  { name: "FINRA", icon: "📊", type: "Equity", desc: "Short interest, dark pool, ADF data", status: "planned", modules: ["dark_pool", "short_interest"] },
  { name: "SSRN/arXiv", icon: "📚", type: "Academic", desc: "Finance research papers, new alpha signals", status: "planned", modules: ["academic_papers"] },
];

export const ideaGeneration = {
  title: "How We Generate the Roadmap",
  process: [
    { step: "🏦 Bloomberg Replication", desc: "Systematically mapping every Bloomberg Terminal function (ECO, WECO, FA, FI, CMDX, FXGO) to free data sources" },
    { step: "🔬 Academic Research", desc: "Every new phase references published finance papers — factor models, market microstructure theory, behavioral finance" },
    { step: "🌍 Government Open Data", desc: "80+ free government APIs worldwide — World Bank, IMF, BLS, Eurostat, central banks, statistical offices" },
    { step: "🤖 AI Self-Evolution", desc: "After each phase, the build agent suggests 3 new features based on what it just built — compounding innovation" },
    { step: "📊 Data Source Expansion", desc: "Each new data source unlocks multiple derived modules — e.g., SEC filings → NLP → supply chain → activist tracking" },
    { step: "🎯 User Signal", desc: "Real trading needs drive priorities — what would a quant trader actually use at 4am before markets open?" },
    { step: "🔗 Cross-Module Synergy", desc: "New phases often combine existing modules — e.g., ML earnings predictor uses options flow + sentiment + technicals" },
  ],
};
