export interface Service {
  id: string;
  name: string;
  phase: number;
  category: string;
  description: string;
  commands: string[];
  mcpTool: string;
  params: string;
  icon: string;
  apiEndpoint?: string; // REST API path e.g. /api/v1/prices?ticker=AAPL
}

// Auto-generate apiEndpoint from service id if not explicitly set
export function getApiEndpoint(s: Service): string {
  if (s.apiEndpoint) return s.apiEndpoint;
  const base = `/api/v1/${s.id.replace(/_/g, '-')}`;
  const firstParam = s.params.split(',')[0]?.trim().replace('?','').replace('{}','').replace('[]','');
  return firstParam ? `${base}?${firstParam}=AAPL` : base;
}

export const categories = [
  { id: "core", name: "Core Market Data", icon: "📊", color: "#13C636" },
  { id: "derivatives", name: "Derivatives & Options", icon: "📈", color: "#00BFFF" },
  { id: "alt-data", name: "Alternative Data", icon: "🔍", color: "#FFD700" },
  { id: "multi-asset", name: "Multi-Asset", icon: "🌍", color: "#FF6B6B" },
  { id: "quant", name: "Quantitative", icon: "🧮", color: "#C0E8FD" },
  { id: "fixed-income", name: "Fixed Income & Macro", icon: "🏦", color: "#9B59B6" },
  { id: "events", name: "Corporate Events", icon: "📰", color: "#E67E22" },
  { id: "intelligence", name: "Intelligence & NLP", icon: "🤖", color: "#1ABC9C" },
  { id: "infrastructure", name: "Infrastructure", icon: "⚙️", color: "#95A5A6" },
];

export const services: Service[] = [
  // Core Market Data
  { id: "prices", name: "Real-Time Prices", phase: 1, category: "core", description: "Live stock prices, historical OHLCV, after-hours data via Yahoo Finance", commands: ["price AAPL", "price AAPL --history 30d"], mcpTool: "get_price", params: "ticker, period?", icon: "💰" },
  { id: "company_profile", name: "Company Profile", phase: 4, category: "core", description: "Company overview, sector, employees, market cap, description", commands: ["profile AAPL"], mcpTool: "get_company_profile", params: "ticker", icon: "🏢" },
  { id: "screener", name: "Stock Screener", phase: 4, category: "core", description: "Filter stocks by market cap, P/E, sector, dividend yield, volume", commands: ["screen --min-cap 10B --sector Technology"], mcpTool: "screen_stocks", params: "filters{}", icon: "🔎" },
  { id: "technicals", name: "Technical Analysis", phase: 3, category: "core", description: "RSI, MACD, Bollinger Bands, moving averages, support/resistance", commands: ["technicals AAPL", "technicals TSLA --indicators rsi,macd"], mcpTool: "get_technicals", params: "ticker, indicators?", icon: "📉" },
  { id: "market_microstructure", name: "Market Microstructure", phase: 22, category: "core", description: "Bid-ask spreads, order flow imbalance, liquidity scoring, market maker activity", commands: ["microstructure-spreads AAPL", "microstructure-flow TSLA", "microstructure-compare AAPL MSFT GOOGL"], mcpTool: "get_microstructure", params: "ticker, analysis_type", icon: "🔬" },

  // Derivatives & Options
  { id: "options", name: "Options Chain", phase: 2, category: "derivatives", description: "Full options chain with Greeks, put/call ratio, implied volatility", commands: ["options AAPL", "options TSLA --expiry 2026-03-21"], mcpTool: "get_options", params: "ticker, expiry?", icon: "📋" },
  { id: "options_flow_scanner", name: "Options Flow Scanner", phase: 6, category: "derivatives", description: "Unusual activity alerts, dark pool prints, sweep detection", commands: ["options-flow AAPL", "options-flow --unusual"], mcpTool: "scan_options_flow", params: "ticker?, unusual_only?", icon: "🌊" },
  { id: "options_gex", name: "Options GEX Tracker", phase: 28, category: "derivatives", description: "Dealer gamma exposure positioning, pin risk at major strikes, hedging flow analysis", commands: ["gex SPY", "pin-risk AAPL", "hedging-flow TSLA"], mcpTool: "get_gex", params: "ticker, analysis_type?", icon: "⚡" },
  { id: "volatility_surface", name: "Volatility Surface", phase: 89, category: "derivatives", description: "IV smile/skew analysis, volatility arbitrage detection, straddle/strangle scanner with probability analysis", commands: ["iv-smile AAPL", "vol-arbitrage TSLA", "straddle-scan NVDA", "strangle-scan SPY --max-days 45"], mcpTool: "analyze_volatility_surface", params: "ticker, action?, expiry?, max_days?", icon: "📊" },

  // Alternative Data
  { id: "news_sentiment", name: "News & Sentiment", phase: 1, category: "alt-data", description: "Aggregated news with NLP sentiment scoring from multiple sources", commands: ["news AAPL", "news TSLA --sentiment"], mcpTool: "get_news_sentiment", params: "ticker, sources?", icon: "📰" },
  { id: "social_sentiment", name: "Social Sentiment", phase: 3, category: "alt-data", description: "Reddit, StockTwits, Twitter sentiment tracking and trends", commands: ["social AAPL", "social GME --source reddit"], mcpTool: "get_social_sentiment", params: "ticker, source?", icon: "💬" },
  { id: "congress_trades", name: "Congress Trades", phase: 3, category: "alt-data", description: "Congressional trading disclosures, politician portfolios, insider timing", commands: ["congress AAPL", "congress --recent 30d"], mcpTool: "get_congress_trades", params: "ticker?, days?", icon: "🏛️" },
  { id: "short_interest", name: "Short Interest", phase: 3, category: "alt-data", description: "Short interest ratio, days to cover, short squeeze candidates", commands: ["short-interest AAPL", "short-interest --squeeze"], mcpTool: "get_short_interest", params: "ticker", icon: "📊" },
  { id: "patent_tracking", name: "Patent Tracking", phase: 11, category: "alt-data", description: "USPTO patent filings, R&D velocity scoring, innovation index", commands: ["patents AAPL", "patents --top-filers"], mcpTool: "get_patents", params: "ticker, limit?", icon: "💡" },
  { id: "job_posting_signals", name: "Job Posting Signals", phase: 12, category: "alt-data", description: "Hiring velocity as leading indicator, department growth, geo expansion", commands: ["jobs AAPL", "jobs TSLA --trend"], mcpTool: "get_job_signals", params: "ticker", icon: "👔" },
  { id: "supply_chain_mapping", name: "Supply Chain Mapping", phase: 13, category: "alt-data", description: "Supplier/customer relationships via SEC NLP, dependency graphs", commands: ["supply-chain AAPL"], mcpTool: "get_supply_chain", params: "ticker", icon: "🔗" },
  { id: "weather_agriculture", name: "Weather & Agriculture", phase: 14, category: "alt-data", description: "NOAA weather data, crop conditions, energy demand signals", commands: ["weather --region midwest", "weather --crop corn"], mcpTool: "get_weather_ag", params: "region?, crop?", icon: "🌾" },
  { id: "activist_investor_tracking", name: "Activist Investors", phase: 19, category: "alt-data", description: "13D filings, campaign tracking, activist targets", commands: ["activists AAPL", "activists --recent"], mcpTool: "get_activist_investors", params: "ticker?", icon: "🎯" },
  { id: "esg_scoring", name: "ESG Scoring", phase: 20, category: "alt-data", description: "Environmental, social, governance metrics and composite scores", commands: ["esg AAPL", "esg --compare AAPL MSFT"], mcpTool: "get_esg_score", params: "ticker", icon: "🌱" },
  { id: "hedge_fund_13f", name: "Hedge Fund 13F", phase: 29, category: "alt-data", description: "Clone top fund positions, track quarterly changes, smart money flow analysis", commands: ["13f 0001067983", "13f-changes 0001067983", "smart-money AAPL", "top-funds"], mcpTool: "get_13f_holdings", params: "fund?, ticker?, action?", icon: "🏦" },

  // Multi-Asset
  { id: "crypto", name: "Cryptocurrency", phase: 4, category: "multi-asset", description: "Real-time crypto prices, market cap, volume via CoinGecko", commands: ["crypto bitcoin", "crypto ethereum --history 7d"], mcpTool: "get_crypto", params: "coin, period?", icon: "₿" },
  { id: "commodities", name: "Commodities", phase: 4, category: "multi-asset", description: "Gold, silver, oil, natural gas, agricultural futures", commands: ["commodity gold", "commodity oil --history 30d"], mcpTool: "get_commodity", params: "commodity, period?", icon: "🛢️" },
  { id: "forex", name: "Forex", phase: 4, category: "multi-asset", description: "Currency pairs, cross rates, historical exchange rates", commands: ["forex EUR/USD", "forex GBP/JPY --history 90d"], mcpTool: "get_forex", params: "pair, period?", icon: "💱" },
  { id: "commodity_futures", name: "Commodity Futures Curves", phase: 44, category: "multi-asset", description: "Contango/backwardation signals, roll yields, term structure analysis", commands: ["futures-curve CL", "contango", "roll-yield GC", "term-structure NG"], mcpTool: "get_commodity_futures", params: "action, symbol?, params?", icon: "📊" },
  { id: "crypto_onchain", name: "Crypto On-Chain Analytics", phase: 43, category: "multi-asset", description: "Whale wallet tracking, token flows, DEX volume, gas fee analysis", commands: ["onchain ETH", "whale-watch BTC", "dex-volume", "gas-fees", "token-flows USDT"], mcpTool: "get_crypto_onchain", params: "action, symbol?, params?", icon: "⛓️" },
  { id: "whale_tracking", name: "Whale Tracking", phase: 43, category: "multi-asset", description: "Track large crypto holders (ETH/BTC whales) with balance monitoring", commands: ["whale-watch BTC --min 100", "whale-watch ETH"], mcpTool: "track_whales", params: "chain, min_balance?", icon: "🐋" },
  { id: "dex_volume", name: "DEX Volume", phase: 43, category: "multi-asset", description: "Decentralized exchange volume across protocols via DeFi Llama", commands: ["dex-volume", "dex-volume --protocol uniswap", "dex-volume --chain ethereum"], mcpTool: "get_dex_volume", params: "protocol?, chain?", icon: "🔄" },
  { id: "gas_fees", name: "Gas Fees", phase: 43, category: "multi-asset", description: "Real-time Ethereum gas prices (safe/standard/fast) with USD costs", commands: ["gas-fees"], mcpTool: "get_gas_fees", params: "", icon: "⛽" },
  { id: "token_flows", name: "Token Flows", phase: 43, category: "multi-asset", description: "Track ERC-20 token transfers and whale movements on Ethereum", commands: ["token-flows USDT", "token-flows USDC --hours 24"], mcpTool: "get_token_flows", params: "token, lookback_hours?", icon: "💸" },

  // Quantitative
  { id: "factor_model", name: "Factor Model", phase: 7, category: "quant", description: "Momentum, value, quality, size, volatility factor scoring", commands: ["factors AAPL", "factors --top momentum"], mcpTool: "get_factor_scores", params: "ticker, factors?", icon: "📐" },
  { id: "factor_zoo", name: "Factor Zoo", phase: 21, category: "quant", description: "400+ published academic factors replicated and scored", commands: ["factor-zoo AAPL", "factor-zoo --category value"], mcpTool: "get_factor_zoo", params: "ticker, category?", icon: "🦁" },
  { id: "portfolio_analytics", name: "Portfolio Analytics", phase: 8, category: "quant", description: "Sharpe, Sortino, max drawdown, correlation matrix, VaR", commands: ["portfolio-analyze portfolio.json"], mcpTool: "analyze_portfolio", params: "holdings[]", icon: "📊" },
  { id: "backtesting", name: "Backtesting", phase: 9, category: "quant", description: "Event-driven backtester with realistic fills, slippage, commission", commands: ["backtest --strategy momentum --period 1y"], mcpTool: "run_backtest", params: "strategy, period, params?", icon: "⏪" },
  { id: "fama_french", name: "Fama-French Regression", phase: 31, category: "quant", description: "Statistical factor attribution and multi-factor risk decomposition with FF 3-factor and 5-factor models", commands: ["fama-french AAPL", "factor-attribution TSLA", "factor-returns --days 30"], mcpTool: "run_fama_french", params: "ticker, model?, period?", icon: "📐" },
  { id: "pairs_trading", name: "Pairs Trading Signals", phase: 32, category: "quant", description: "Cointegration detection, mean reversion opportunities, spread monitoring", commands: ["pairs-scan beverage", "cointegration KO PEP", "spread-monitor AAPL MSFT --period 60d"], mcpTool: "pairs_trading", params: "action, symbols, params?", icon: "🔗" },
  { id: "sector_rotation", name: "Sector Rotation Model", phase: 33, category: "quant", description: "Economic cycle indicators, relative strength rotation strategies", commands: ["sector-rotation 60", "sector-momentum 90", "economic-cycle"], mcpTool: "sector_rotation", params: "action, lookback?", icon: "🔄" },
  { id: "monte_carlo", name: "Monte Carlo Simulation", phase: 34, category: "quant", description: "Scenario analysis, probabilistic forecasting, tail risk modeling with GBM and bootstrap methods", commands: ["monte-carlo AAPL --simulations 10000 --days 252", "var TSLA --confidence 0.95 0.99", "scenario NVDA --days 90"], mcpTool: "monte_carlo", params: "action, ticker, params?", icon: "🎲" },
  { id: "kalman_filter", name: "Kalman Filter Trends", phase: 35, category: "quant", description: "Smooth price trend extraction using state-space models", commands: ["kalman AAPL", "kalman TSLA --period 1y"], mcpTool: "kalman_filter", params: "ticker, period?", icon: "📡" },
  { id: "adaptive_ma", name: "Adaptive Moving Average", phase: 35, category: "quant", description: "Self-adjusting moving averages with crossover signals", commands: ["adaptive-ma AAPL", "adaptive-ma SPY --period 6mo"], mcpTool: "adaptive_ma", params: "ticker, period?", icon: "📊" },
  { id: "regime_detect", name: "Regime Detection", phase: 35, category: "quant", description: "Market regime changes via innovation variance (trending vs mean-reverting)", commands: ["regime-detect SPY", "regime-detect TSLA --window 30"], mcpTool: "regime_detect", params: "ticker, period?, window?", icon: "🔀" },
  { id: "black_litterman", name: "Black-Litterman Allocation", phase: 36, category: "quant", description: "Combine market equilibrium with investor views for portfolio construction", commands: ["black-litterman --tickers AAPL,MSFT,GOOGL --views AAPL:0.20", "equilibrium-returns --tickers SPY,QQQ,IWM", "portfolio-optimize --tickers AAPL,MSFT,GOOGL"], mcpTool: "black_litterman", params: "action, tickers, views?, params?", icon: "⚖️" },
  { id: "walk_forward", name: "Walk-Forward Optimization", phase: 37, category: "quant", description: "Out-of-sample strategy tuning with rolling windows to prevent overfitting", commands: ["walk-forward SPY --strategy sma-crossover", "overfit-check AAPL", "param-stability TSLA"], mcpTool: "walk_forward_optimize", params: "action, ticker, strategy?, params?", icon: "⏩" },
  { id: "multi_timeframe", name: "Multi-Timeframe Analysis", phase: 38, category: "quant", description: "Combine signals from daily/weekly/monthly charts for confirmation", commands: ["mtf AAPL", "trend-alignment TSLA", "signal-confluence NVDA"], mcpTool: "multi_timeframe_analysis", params: "action, ticker", icon: "📊" },
  { id: "order_book", name: "Order Book Depth", phase: 39, category: "quant", description: "Level 2 data analysis, bid-ask imbalance, hidden liquidity detection", commands: ["order-book AAPL --levels 10", "bid-ask TSLA", "liquidity SPY", "imbalance NVDA --period 5d", "support-resistance AAPL --period 6mo"], mcpTool: "order_book_analysis", params: "action, ticker, params?", icon: "📖" },
  { id: "neural_prediction", name: "Neural Price Prediction", phase: 85, category: "quant", description: "LSTM and statistical models for multi-horizon price forecasting (1d, 5d, 20d) with uncertainty quantification and confidence intervals", commands: ["predict-price AAPL --horizon 5d", "prediction-confidence TSLA", "model-comparison NVDA", "prediction-backtest MSFT --years 1"], mcpTool: "neural_price_prediction", params: "action, ticker, horizon?, years?", icon: "🧠" },
  { id: "orderbook_imbalance", name: "Order Book Imbalance Tracker", phase: 86, category: "quant", description: "Real-time Level 1 bid/ask imbalance analysis, volume-based signals, accumulation/distribution detection for short-term price prediction", commands: ["orderbook-imbalance AAPL", "volume-imbalance NVDA --period 1d --interval 5m", "accumulation TSLA --period 5d --interval 1h", "microstructure-signal MSFT", "orderbook-compare AAPL MSFT GOOGL TSLA NVDA", "spread-dynamics SPY --period 1d --interval 5m"], mcpTool: "orderbook_level1_imbalance", params: "ticker", icon: "⚖️" },
  { id: "volume_imbalance", name: "Volume Imbalance Analysis", phase: 86, category: "quant", description: "Intraday up/down volume analysis with price-volume divergence detection", commands: ["volume-imbalance NVDA --period 1d --interval 5m"], mcpTool: "orderbook_volume_imbalance", params: "ticker, period?, interval?", icon: "📊" },
  { id: "accumulation_distribution", name: "Accumulation/Distribution", phase: 86, category: "quant", description: "Detect smart money accumulation patterns using OBV and Money Flow Index", commands: ["accumulation TSLA --period 5d --interval 1h"], mcpTool: "orderbook_accumulation", params: "ticker, period?, interval?", icon: "💰" },
  { id: "microstructure_signal", name: "Microstructure Signal", phase: 86, category: "quant", description: "Composite trading signal combining order book imbalance, volume analysis, and accumulation indicators", commands: ["microstructure-signal MSFT"], mcpTool: "orderbook_microstructure_signal", params: "ticker", icon: "📡" },
  { id: "orderbook_compare", name: "Order Book Comparison", phase: 86, category: "quant", description: "Batch analysis and ranking of order book signals across multiple tickers", commands: ["orderbook-compare AAPL MSFT GOOGL TSLA NVDA"], mcpTool: "orderbook_compare_signals", params: "tickers[]", icon: "🔍" },
  { id: "spread_dynamics", name: "Spread Dynamics", phase: 86, category: "quant", description: "Bid-ask spread analysis over time with liquidity assessment and trend detection", commands: ["spread-dynamics SPY --period 1d --interval 5m"], mcpTool: "orderbook_spread_dynamics", params: "ticker, period?, interval?", icon: "📉" },
  { id: "ml_stock_screening", name: "ML Stock Screening", phase: 90, category: "quant", description: "Multi-factor machine learning stock screening with Random Forest and Gradient Boosting models, walk-forward validation, and auto-rebalancing portfolio construction", commands: ["ml-screen --top 20", "ml-validate --splits 5", "ml-portfolio --top 20 --rebalance-days 30", "ml-importance"], mcpTool: "ml_screen_stocks", params: "top_n?, universe?", icon: "🤖" },
  { id: "tca_spread", name: "Bid-Ask Spread Analysis", phase: 75, category: "quant", description: "Real-time bid-ask spread analysis with cost estimation in basis points", commands: ["tca-spread AAPL"], mcpTool: "tca_bid_ask_spread", params: "ticker", icon: "💱" },
  { id: "tca_impact", name: "Market Impact Estimation", phase: 75, category: "quant", description: "Estimate market impact for large trades using Kyle's Lambda and Almgren-Chriss models", commands: ["tca-impact AAPL --trade-size 5000000"], mcpTool: "tca_market_impact", params: "ticker, trade_size_usd, period?", icon: "📊" },
  { id: "tca_shortfall", name: "Implementation Shortfall", phase: 75, category: "quant", description: "Calculate implementation shortfall (Perold 1988) for executed trades with performance grading", commands: ["tca-shortfall AAPL --decision-price 270.00 --exec-prices 270.10 270.15 270.25 --exec-sizes 1000 1500 2000 --side buy"], mcpTool: "tca_implementation_shortfall", params: "ticker, decision_price, execution_prices, execution_sizes, side", icon: "📈" },
  { id: "tca_optimize", name: "Execution Schedule Optimization", phase: 75, category: "quant", description: "Generate optimal execution schedule using TWAP/VWAP/POV strategies", commands: ["tca-optimize AAPL --total-shares 50000 --window 240 --strategy vwap"], mcpTool: "tca_optimize_execution", params: "ticker, total_shares, execution_window_minutes, strategy?", icon: "⏱️" },
  { id: "tca_compare", name: "Execution Strategy Comparison", phase: 75, category: "quant", description: "Compare transaction costs across different execution strategies (immediate/TWAP/VWAP/dark pool)", commands: ["tca-compare AAPL --trade-size 10000000"], mcpTool: "tca_compare_strategies", params: "ticker, trade_size_usd", icon: "🔀" },

  // Fixed Income & Macro
  { id: "macro", name: "Macro Indicators", phase: 2, category: "fixed-income", description: "GDP, CPI, unemployment, interest rates, Fed funds", commands: ["macro gdp", "macro cpi --history 5y"], mcpTool: "get_macro", params: "indicator, period?", icon: "🏦" },
  { id: "bond_analytics", name: "Bond Analytics", phase: 15, category: "fixed-income", description: "Yield curves, credit spreads, duration, convexity analysis", commands: ["bonds yield-curve", "bonds spread --rating BBB"], mcpTool: "get_bond_analytics", params: "analysis_type, params?", icon: "📜" },
  { id: "cds_spreads", name: "CDS Spreads", phase: 30, category: "fixed-income", description: "Sovereign and corporate credit risk signals from credit default swap markets", commands: ["cds AAPL", "cds --credit-spreads", "cds --sovereign Italy"], mcpTool: "get_cds_spreads", params: "entity?, action?", icon: "💳" },
  { id: "fed_policy", name: "Fed Policy Prediction", phase: 45, category: "fixed-income", description: "FOMC analysis, dot plot tracking, rate hike probability scoring via fed funds futures", commands: ["fed-watch", "rate-probability", "fomc-calendar", "dot-plot", "yield-curve", "current-rate"], mcpTool: "get_fed_policy", params: "analysis_type", icon: "🏛️" },
  { id: "regulatory_calendar", name: "Regulatory Event Calendar", phase: 78, category: "fixed-income", description: "FOMC, CPI, GDP, NFP tracking with historical market reaction backtests and volatility forecasts", commands: ["econ-calendar", "event-reaction CPI", "event-volatility FOMC", "event-backtest NFP --years 5"], mcpTool: "get_regulatory_calendar", params: "action, eventType?, years?", icon: "📅" },

  // Corporate Events
  { id: "sec_edgar", name: "SEC Filings", phase: 1, category: "events", description: "10-K, 10-Q, 8-K filings from SEC EDGAR with full text", commands: ["sec AAPL", "sec TSLA --type 10-K"], mcpTool: "get_sec_filings", params: "ticker, form_type?", icon: "📑" },
  { id: "sec_nlp", name: "SEC NLP Analysis", phase: 16, category: "events", description: "Risk factor extraction, MD&A sentiment, change detection", commands: ["sec-nlp AAPL --section risk", "sec-nlp TSLA --diff"], mcpTool: "analyze_sec_filing", params: "ticker, section?, diff?", icon: "🔬" },
  { id: "earnings", name: "Earnings Calendar", phase: 2, category: "events", description: "Upcoming earnings dates, EPS estimates, beat/miss history", commands: ["earnings AAPL", "earnings --upcoming 7d"], mcpTool: "get_earnings", params: "ticker?, period?", icon: "📅" },
  { id: "earnings_transcripts", name: "Earnings Transcripts", phase: 5, category: "events", description: "Full call transcripts with NLP — key quotes, guidance, sentiment", commands: ["transcript AAPL --quarter Q1-2026"], mcpTool: "get_earnings_transcript", params: "ticker, quarter?", icon: "🎤" },
  { id: "dividends", name: "Dividends", phase: 2, category: "events", description: "Dividend history, yield, payout ratio, ex-dates, growth rate", commands: ["dividends AAPL", "dividends --aristocrats"], mcpTool: "get_dividends", params: "ticker", icon: "💎" },
  { id: "analyst_ratings", name: "Analyst Ratings", phase: 4, category: "events", description: "Consensus ratings, price targets, upgrades/downgrades", commands: ["ratings AAPL", "ratings TSLA --history"], mcpTool: "get_analyst_ratings", params: "ticker", icon: "⭐" },
  { id: "ipo_spac_tracker", name: "IPO & SPAC Tracker", phase: 17, category: "events", description: "Upcoming IPOs, SPAC arbitrage, lock-up expiry dates", commands: ["ipos --upcoming", "spacs --arbitrage"], mcpTool: "get_ipo_spac", params: "type, filter?", icon: "🚀" },
  { id: "ma_deal_flow", name: "M&A Deal Flow", phase: 18, category: "events", description: "Announced deals, merger arb spreads, completion probability", commands: ["ma --active", "ma ATVI --spread"], mcpTool: "get_ma_deals", params: "ticker?, active_only?", icon: "🤝" },
  { id: "etf_holdings", name: "ETF Holdings", phase: 2, category: "events", description: "ETF constituents, sector weights, overlap analysis", commands: ["etf SPY", "etf QQQ --overlap SPY"], mcpTool: "get_etf_holdings", params: "ticker, compare?", icon: "🗂️" },

  // Intelligence
  { id: "research_reports", name: "Research Reports", phase: 23, category: "intelligence", description: "AI-generated equity research with LLM synthesis across all data sources", commands: ["research-report AAPL --output report.md"], mcpTool: "generate_research_report", params: "ticker, format?", icon: "📝" },
  { id: "alerts", name: "Smart Alerts", phase: 10, category: "infrastructure", description: "Price alerts, volume spikes, RSI thresholds, earnings triggers", commands: ["alert set AAPL --price-above 250", "alert list"], mcpTool: "manage_alerts", params: "action, ticker?, conditions?", icon: "🔔" },
  { id: "smart_alert_delivery", name: "Smart Alert Delivery", phase: 40, category: "infrastructure", description: "Multi-channel notifications (email, SMS, Discord, Telegram) with rate limiting, cooldown periods, and delivery tracking", commands: ["alert-create AAPL --condition 'price>200'", "alert-check --symbols AAPL,TSLA", "alert-history --symbol AAPL"], mcpTool: "manage_smart_alerts", params: "action, params?", icon: "📬" },
  { id: "alert_dsl", name: "Custom Alert DSL", phase: 42, category: "infrastructure", description: "Domain-specific language for complex multi-condition alert rules", commands: ["dsl-eval AAPL \"price > 200 AND rsi < 30\"", "dsl-scan \"rsi < 25\" --universe SP500", "dsl-help"], mcpTool: "evaluate_alert_dsl", params: "expression, ticker?, universe?", icon: "🔧" },
  { id: "alert_backtest", name: "Alert Backtesting", phase: 41, category: "infrastructure", description: "Test alert strategies historically, measure signal quality, false positive rates", commands: ["alert-backtest AAPL --condition 'rsi<30'"], mcpTool: "backtest_alert", params: "ticker, condition, period?", icon: "🎯" },
  { id: "signal_quality", name: "Signal Quality Analysis", phase: 41, category: "infrastructure", description: "Rank alert conditions by quality score, hit rate, profit factor", commands: ["signal-quality AAPL --period 1y"], mcpTool: "analyze_signal_quality", params: "ticker, period?", icon: "🏆" },
  { id: "alert_potential", name: "Alert Potential", phase: 41, category: "infrastructure", description: "Measure alert trigger frequency and volatility metrics", commands: ["alert-potential AAPL --period 1y"], mcpTool: "get_alert_potential", params: "ticker, period?", icon: "📊" },
  { id: "alert_dashboard", name: "Alert Backtesting Dashboard", phase: 80, category: "infrastructure", description: "Visualize historical alert performance with profit factor, Sharpe ratio, win rate, and max drawdown for RSI, volume spike, breakout, and earnings alerts", commands: ["dashboard-backtest rsi --ticker AAPL --years 3", "dashboard-performance", "dashboard-optimize TSLA --alert-type rsi", "dashboard-report"], mcpTool: "alert_dashboard", params: "action, ticker?, alertType?, years?, holdDays?", icon: "📊" },
  
  // Satellite Imagery Proxies
  { id: "satellite_proxy", name: "Satellite Proxy Analysis", phase: 46, category: "alt-data", description: "Company-specific satellite proxy: Google Trends foot traffic, brand interest correlation with stock momentum", commands: ["satellite-proxy WMT", "satellite-proxy AAPL"], mcpTool: "get_satellite_proxy", params: "ticker", icon: "🛰️" },
  { id: "shipping_index", name: "Shipping Activity Index", phase: 46, category: "alt-data", description: "Baltic Dry Index proxies: shipping stock performance, global trade activity indicators", commands: ["shipping-index"], mcpTool: "get_shipping_index", params: "", icon: "🚢" },
  { id: "construction_activity", name: "Construction Activity", phase: 46, category: "alt-data", description: "Construction employment, building permits, industrial production - leading indicators for materials/industrials", commands: ["construction-activity"], mcpTool: "get_construction_activity", params: "", icon: "🏗️" },
  { id: "foot_traffic", name: "Foot Traffic Proxy", phase: 46, category: "alt-data", description: "Google Trends brand search interest as retail foot traffic proxy", commands: ["foot-traffic AAPL", "foot-traffic WMT"], mcpTool: "get_foot_traffic", params: "ticker", icon: "👟" },
  { id: "economic_index", name: "Economic Activity Index", phase: 46, category: "alt-data", description: "Composite index: construction, shipping, consumer sentiment, retail sales - macro activity scoring", commands: ["economic-index"], mcpTool: "get_economic_index", params: "", icon: "📊" },
  
  // Earnings Call NLP
  { id: "earnings_tone", name: "Earnings Call Tone Analysis", phase: 47, category: "intelligence", description: "Loughran-McDonald sentiment, hedging language detection, tone shift between prepared remarks and Q&A", commands: ["earnings-tone AAPL", "earnings-tone TSLA"], mcpTool: "analyze_earnings_tone", params: "ticker", icon: "🎤" },
  { id: "confidence_score", name: "Management Confidence Score", phase: 47, category: "intelligence", description: "Linguistic markers of confidence, assertive vs hedging language, composite scoring", commands: ["confidence-score AAPL", "confidence-score NVDA"], mcpTool: "get_confidence_score", params: "ticker", icon: "💪" },
  { id: "dodge_detect", name: "Question Dodging Detection", phase: 47, category: "intelligence", description: "Q&A evasiveness analysis, response length vs question complexity, vague answer detection", commands: ["dodge-detect AAPL", "dodge-detect TSLA"], mcpTool: "detect_question_dodging", params: "ticker", icon: "🎯" },
  
  // Product Launch Tracker
  { id: "launch_summary", name: "Product Launch Summary", phase: 50, category: "alt-data", description: "Comprehensive product launch analysis: social buzz, sentiment, media coverage, composite launch score", commands: ["launch-summary 'iPhone 16'", "launch-summary 'Tesla Cybertruck'"], mcpTool: "get_launch_summary", params: "product_name", icon: "🚀" },
  { id: "buzz_tracking", name: "Buzz Tracking", phase: 50, category: "alt-data", description: "Google Trends search interest over time, peak buzz, trending queries for product launches", commands: ["buzz-tracking 'PlayStation 5'", "buzz-tracking 'Apple Vision Pro'"], mcpTool: "get_google_trends_buzz", params: "product_name, timeframe?", icon: "📈" },
  { id: "reddit_sentiment", name: "Reddit Sentiment", phase: 50, category: "alt-data", description: "Analyze Reddit mentions, sentiment scoring, top discussions about new products", commands: ["reddit-sentiment 'iPhone 16'", "reddit-sentiment 'Samsung Galaxy S24'"], mcpTool: "get_reddit_sentiment", params: "product_name, subreddit?, limit?", icon: "💬" },
  { id: "news_coverage", name: "News Coverage", phase: 50, category: "alt-data", description: "Track media coverage velocity, article count, top sources via Google News RSS", commands: ["news-coverage 'iPhone 16'", "news-coverage 'Tesla Model Y'"], mcpTool: "get_news_coverage", params: "product_name, days?", icon: "📰" },
  { id: "preorder_velocity", name: "Pre-Order Velocity", phase: 50, category: "alt-data", description: "Estimate pre-order velocity using search trend acceleration as proxy", commands: ["preorder-velocity 'iPhone 16'", "preorder-velocity 'PlayStation 5'"], mcpTool: "track_preorder_velocity", params: "product_name, ticker?", icon: "🏃" },
  { id: "trending_products", name: "Trending Products", phase: 50, category: "alt-data", description: "Discover currently trending products by category (tech, automotive, consumer, entertainment)", commands: ["trending-products tech", "trending-products automotive"], mcpTool: "get_trending_products", params: "category", icon: "🔥" },
  
  // Peer Network Analysis
  { id: "peer_network", name: "Peer Network Analysis", phase: 48, category: "intelligence", description: "Company relationship mapping via SEC 10-K, revenue concentration, systemic risk scoring", commands: ["peer-network AAPL", "peer-network TSLA"], mcpTool: "analyze_peer_network", params: "ticker", icon: "🕸️" },
  { id: "network_compare", name: "Network Comparison", phase: 48, category: "intelligence", description: "Compare peer networks across multiple companies, identify common connections", commands: ["compare-networks AAPL,MSFT,GOOGL"], mcpTool: "compare_networks", params: "tickers[]", icon: "🔗" },
  { id: "dependency_map", name: "Dependency Mapping", phase: 48, category: "intelligence", description: "Map revenue dependencies and supply chain relationships recursively", commands: ["map-dependencies AAPL"], mcpTool: "map_dependencies", params: "ticker, depth?", icon: "🗺️" },
  
  // Political Risk Scoring
  { id: "geopolitical_events", name: "Geopolitical Events", phase: 49, category: "alt-data", description: "Real-time geopolitical event tracking via GDELT with risk scoring", commands: ["geopolitical-events", "geopolitical-events --country Russia", "geopolitical-events --keywords sanctions"], mcpTool: "get_geopolitical_events", params: "country?, keywords?, hours?", icon: "🌍" },
  { id: "sanctions_search", name: "Sanctions Search", phase: 49, category: "alt-data", description: "OFAC sanctions list search by entity, country, or program", commands: ["sanctions-search --entity Russia", "sanctions-search --type country"], mcpTool: "search_sanctions", params: "entity?, type?", icon: "⚖️" },
  { id: "regulatory_changes", name: "Regulatory Changes", phase: 49, category: "alt-data", description: "Track regulatory changes by sector with impact scoring", commands: ["regulatory-changes --sector finance", "regulatory-changes --country US --days 30"], mcpTool: "track_regulatory_changes", params: "sector?, country?, days?", icon: "📜" },
  { id: "country_risk", name: "Country Risk Indicators", phase: 49, category: "alt-data", description: "World Bank governance indicators for country risk assessment", commands: ["country-risk USA", "country-risk CHN"], mcpTool: "get_country_risk", params: "country_code", icon: "🗺️" },
  
  // Revenue Quality Analysis
  { id: "revenue_quality", name: "Revenue Quality Analysis", phase: 52, category: "intelligence", description: "Comprehensive revenue quality analysis: cash flow vs earnings divergence, DSO trends, accruals ratio", commands: ["revenue-quality AAPL"], mcpTool: "analyze_revenue_quality", params: "ticker", icon: "💎" },
  { id: "dso_trends", name: "DSO Trends", phase: 52, category: "intelligence", description: "Days Sales Outstanding trend analysis with visualization data", commands: ["dso-trends AAPL"], mcpTool: "get_dso_trends", params: "ticker", icon: "📊" },
  { id: "channel_stuffing", name: "Channel Stuffing Detection", phase: 52, category: "intelligence", description: "Detect channel stuffing red flags: receivables vs revenue growth mismatch", commands: ["channel-stuffing AAPL"], mcpTool: "detect_channel_stuffing", params: "ticker", icon: "🚨" },
  { id: "cash_flow_divergence", name: "Cash Flow vs Earnings", phase: 52, category: "intelligence", description: "Analyze operating cash flow vs net income divergence over time", commands: ["cash-flow-divergence AAPL"], mcpTool: "analyze_cash_flow_divergence", params: "ticker", icon: "💰" },
  
  // Earnings Quality Metrics (Phase 59)
  { id: "earnings_quality", name: "Earnings Quality Metrics", phase: 59, category: "intelligence", description: "Fraud and distress detection: Accruals ratio, Beneish M-Score, Altman Z-Score", commands: ["earnings-quality AAPL"], mcpTool: "analyze_earnings_quality", params: "ticker", icon: "🔍" },
  { id: "accruals_trend", name: "Accruals Ratio Trend", phase: 59, category: "intelligence", description: "Accruals ratio trend analysis over 4 periods with manipulation risk flags", commands: ["accruals-trend AAPL"], mcpTool: "get_accruals_trend", params: "ticker", icon: "📈" },
  { id: "fraud_indicators", name: "Fraud Indicators", phase: 59, category: "intelligence", description: "Quick fraud/distress red flags summary from all three metrics", commands: ["fraud-indicators AAPL"], mcpTool: "get_fraud_indicators", params: "ticker", icon: "🚨" },
  
  // Executive Compensation (Phase 51)
  { id: "exec_comp", name: "Executive Compensation", phase: 51, category: "alt-data", description: "Executive compensation breakdown from SEC DEF 14A proxy filings and Yahoo Finance", commands: ["exec-comp AAPL"], mcpTool: "get_exec_comp", params: "ticker", icon: "💼" },
  { id: "pay_performance", name: "Pay-for-Performance Analysis", phase: 51, category: "alt-data", description: "Analyze CEO compensation correlation with stock returns and alignment score", commands: ["pay-performance TSLA"], mcpTool: "analyze_pay_performance", params: "ticker", icon: "📊" },
  { id: "comp_peer_compare", name: "Compensation Peer Comparison", phase: 51, category: "alt-data", description: "Compare executive compensation across peer companies with percentile rankings", commands: ["comp-peer-compare MSFT"], mcpTool: "compare_comp_peers", params: "ticker, peers?", icon: "🔍" },
  { id: "shareholder_alignment", name: "Shareholder Alignment", phase: 51, category: "alt-data", description: "Insider ownership, recent transactions, stock-based compensation alignment metrics", commands: ["shareholder-alignment GOOGL"], mcpTool: "get_shareholder_alignment", params: "ticker", icon: "🤝" },
  
  // Share Buyback Analysis (Phase 56)
  { id: "buyback_analysis", name: "Full Buyback Analysis", phase: 56, category: "events", description: "Comprehensive buyback report: authorization vs execution, dilution impact, ROI calculation", commands: ["buyback-analysis AAPL"], mcpTool: "get_buyback_analysis", params: "ticker", icon: "🔄" },
  { id: "share_count_trend", name: "Share Count Trend", phase: 56, category: "events", description: "Shares outstanding history and quarter-over-quarter changes", commands: ["share-count-trend MSFT"], mcpTool: "get_share_count_trend", params: "ticker", icon: "📊" },
  { id: "buyback_yield", name: "Buyback Yield", phase: 56, category: "events", description: "Buyback yield calculation (buybacks/market cap), total shareholder yield", commands: ["buyback-yield GOOGL"], mcpTool: "get_buyback_yield", params: "ticker", icon: "💰" },
  { id: "dilution_impact", name: "Dilution Impact", phase: 56, category: "events", description: "Stock-based compensation dilution vs buyback offset analysis", commands: ["dilution-impact META"], mcpTool: "get_dilution_impact", params: "ticker", icon: "⚖️" },
  
  // Peer Earnings Comparison (Phase 53)
  { id: "peer_earnings", name: "Peer Earnings Comparison", phase: 53, category: "events", description: "Compare earnings beat/miss patterns across sector peers with relative performance", commands: ["peer-earnings AAPL"], mcpTool: "get_peer_earnings", params: "ticker", icon: "📊" },
  { id: "beat_miss_history", name: "Beat/Miss Pattern Analysis", phase: 53, category: "events", description: "Historical earnings beat/miss patterns, consecutive streaks, surprise volatility", commands: ["beat-miss-history TSLA"], mcpTool: "get_beat_miss_pattern", params: "ticker", icon: "🎯" },
  { id: "guidance_tracker", name: "Guidance Trends", phase: 53, category: "events", description: "Management guidance revisions, analyst upgrade/downgrade trends, forward estimates", commands: ["guidance-tracker MSFT"], mcpTool: "track_guidance", params: "ticker", icon: "📈" },
  { id: "estimate_dispersion", name: "Analyst Estimate Dispersion", phase: 53, category: "events", description: "Analyst estimate spread, consensus uncertainty, coefficient of variation analysis", commands: ["estimate-dispersion NVDA"], mcpTool: "analyze_estimate_dispersion", params: "ticker", icon: "📉" },
  
  // Estimate Revision Tracker (Phase 62)
  { id: "analyst_recommendations", name: "Analyst Recommendations", phase: 62, category: "events", description: "Current analyst recommendation distribution, consensus rating, momentum score and trend", commands: ["recommendations AAPL"], mcpTool: "get_analyst_recommendations", params: "ticker", icon: "⭐" },
  { id: "estimate_revisions", name: "Estimate Revisions", phase: 62, category: "events", description: "EPS estimate tracking with dispersion analysis and growth forecasts", commands: ["revisions TSLA"], mcpTool: "get_estimate_revisions", params: "ticker", icon: "📊" },
  { id: "revision_velocity", name: "Revision Velocity", phase: 62, category: "events", description: "Calculate analyst revision velocity, momentum change, and trend direction", commands: ["velocity MSFT --lookback 3"], mcpTool: "get_revision_velocity", params: "ticker, lookback_months?", icon: "📈" },
  { id: "price_targets", name: "Price Target Changes", phase: 62, category: "events", description: "Analyst price target tracking with upside/downside analysis and target range", commands: ["targets NVDA"], mcpTool: "get_price_target_changes", params: "ticker", icon: "🎯" },
  { id: "estimate_momentum", name: "Estimate Momentum Summary", phase: 62, category: "events", description: "Comprehensive momentum report with composite score combining recommendations, revisions, velocity, and targets", commands: ["summary GOOGL"], mcpTool: "get_estimate_momentum_summary", params: "ticker", icon: "🚀" },
  
  // Crypto Correlation Indicators (Phase 54)
  { id: "btc_dominance", name: "BTC Dominance", phase: 54, category: "multi-asset", description: "Bitcoin dominance trend, altcoin season signal, market regime detection", commands: ["btc-dominance"], mcpTool: "get_btc_dominance", params: "", icon: "₿" },
  { id: "altcoin_season", name: "Altcoin Season Index", phase: 54, category: "multi-asset", description: "Percentage of top 50 altcoins outperforming BTC, season classification, top performers", commands: ["altcoin-season"], mcpTool: "get_altcoin_season", params: "", icon: "🪙" },
  { id: "defi_tvl_correlation", name: "DeFi TVL Correlation", phase: 54, category: "multi-asset", description: "DeFi Total Value Locked correlation with NASDAQ/tech stocks, regime analysis", commands: ["defi-tvl-correlation"], mcpTool: "get_defi_tvl_correlation", params: "", icon: "🦙" },
  { id: "crypto_equity_corr", name: "Crypto-Equity Correlation Matrix", phase: 54, category: "multi-asset", description: "Correlation matrix between crypto (BTC/ETH/BNB) and tech stocks (FAANG), market regime", commands: ["crypto-equity-corr"], mcpTool: "get_crypto_equity_correlation", params: "", icon: "🔗" },
  
  // Tax Loss Harvesting (Phase 55)
  { id: "tlh_scan", name: "TLH Portfolio Scan", phase: 55, category: "quant", description: "Scan portfolio for tax loss harvesting candidates with YTD returns and loss potential", commands: ["tlh-scan AAPL,TSLA,MSFT,AMZN,META"], mcpTool: "scan_tlh_opportunities", params: "tickers[]", icon: "💸" },
  { id: "wash_sale_check", name: "Wash Sale Rule Check", phase: 55, category: "quant", description: "Check 30-day wash sale window before and after sale date to avoid IRS violations", commands: ["wash-sale-check TSLA 2025-01-15"], mcpTool: "check_wash_sale", params: "ticker, sale_date", icon: "⚠️" },
  { id: "tax_savings", name: "Tax Savings Estimator", phase: 55, category: "quant", description: "Estimate potential tax savings from harvesting capital losses with position details", commands: ["tax-savings AAPL --cost-basis 180 --shares 100"], mcpTool: "estimate_tax_savings", params: "ticker, cost_basis, shares, tax_rate?", icon: "💰" },
  { id: "tlh_replacements", name: "Sector Replacement Suggestions", phase: 55, category: "quant", description: "Suggest replacement ETFs in same sector to maintain exposure without wash sale", commands: ["tlh-replacements TSLA"], mcpTool: "suggest_tlh_replacements", params: "ticker", icon: "🔄" },
  
  // Dividend Sustainability (Phase 57)
  { id: "dividend_health", name: "Dividend Health Report", phase: 57, category: "events", description: "Comprehensive dividend sustainability: payout ratio, FCF coverage, growth rate, aristocrat status, cut risk", commands: ["dividend-health AAPL"], mcpTool: "get_dividend_health", params: "ticker", icon: "💎" },
  { id: "payout_ratio", name: "Payout Ratio Trends", phase: 57, category: "events", description: "Payout ratio trend analysis with 5-year history, sustainability assessment", commands: ["payout-ratio JNJ"], mcpTool: "get_payout_ratio", params: "ticker", icon: "📊" },
  { id: "fcf_coverage", name: "FCF Dividend Coverage", phase: 57, category: "events", description: "Free cash flow dividend coverage analysis, trend direction, adequacy assessment", commands: ["fcf-coverage KO"], mcpTool: "get_fcf_coverage", params: "ticker", icon: "💰" },
  { id: "dividend_cut_risk", name: "Dividend Cut Probability", phase: 57, category: "events", description: "Probability score (0-100) of dividend cut with risk factors and mitigation analysis", commands: ["dividend-cut-risk T"], mcpTool: "get_dividend_cut_risk", params: "ticker", icon: "⚠️" },
  
  // Institutional Ownership (Phase 58)
  { id: "13f_changes", name: "13F Holdings Changes", phase: 58, category: "alt-data", description: "Track institutional 13F quarterly changes: new positions, increases, decreases, exits across top funds", commands: ["13f-changes AAPL"], mcpTool: "track_13f_changes", params: "ticker, filers?", icon: "📊" },
  { id: "whale_accumulation", name: "Whale Accumulation Detector", phase: 58, category: "alt-data", description: "Detect institutional accumulation or distribution patterns over multiple quarters with trend analysis", commands: ["whale-accumulation TSLA"], mcpTool: "detect_whale_accumulation", params: "ticker, lookback_quarters?", icon: "🐋" },
  { id: "top_institutional_holders", name: "Top Institutional Holders", phase: 58, category: "alt-data", description: "Top institutional shareholders with ownership concentration metrics and smart money positioning", commands: ["top-holders NVDA --limit 20"], mcpTool: "get_top_institutional_holders", params: "ticker, limit?", icon: "🏦" },
  { id: "smart_money_flow", name: "Smart Money Tracker", phase: 58, category: "alt-data", description: "Track famous investor positions (Buffett, Ackman, Burry, Klarman, etc.) from 13F filings", commands: ["smart-money GOOGL"], mcpTool: "get_smart_money_flow", params: "ticker", icon: "🧠" },
  
  // Dark Pool Tracker (Phase 61)
  { id: "dark_pool_volume", name: "Dark Pool Volume Estimate", phase: 61, category: "alt-data", description: "Estimate dark pool volume percentage (OTC vs lit exchange ratio), institutional trading signals", commands: ["dark-pool-volume AAPL"], mcpTool: "get_dark_pool_volume", params: "ticker", icon: "🌑" },
  { id: "block_trades", name: "Block Trade Detection", phase: 61, category: "alt-data", description: "Detect large institutional block trades (>10k shares or $200k value) with accumulation signals", commands: ["block-trades TSLA"], mcpTool: "detect_block_trades", params: "ticker, days?", icon: "📦" },
  { id: "institutional_accumulation", name: "Institutional Accumulation", phase: 61, category: "alt-data", description: "Analyze institutional accumulation vs distribution patterns using volume-price divergence and OBV", commands: ["institutional-accumulation NVDA --period 30"], mcpTool: "analyze_institutional_accumulation", params: "ticker, period?", icon: "📈" },
  { id: "off_exchange_ratio", name: "Off-Exchange Trading Ratio", phase: 61, category: "alt-data", description: "Track off-exchange (dark pool + OTC) vs lit exchange trading ratio trends over time", commands: ["off-exchange-ratio SPY --period 20"], mcpTool: "get_off_exchange_ratio", params: "ticker, period?", icon: "⚖️" },
  
  // Corporate Action Calendar (Phase 63)
  { id: "corporate_calendar", name: "Corporate Action Calendar", phase: 63, category: "events", description: "Upcoming corporate actions: dividend ex-dates, stock splits, special distributions with impact analysis", commands: ["corporate-calendar AAPL"], mcpTool: "get_corporate_calendar", params: "ticker", icon: "📅" },
  { id: "split_history", name: "Stock Split History", phase: 63, category: "events", description: "Stock split history with pre/post price impact analysis, forward vs reverse split classification", commands: ["split-history TSLA"], mcpTool: "get_split_history", params: "ticker, lookback_years?", icon: "📊" },
  { id: "dividend_calendar", name: "Dividend Calendar", phase: 63, category: "events", description: "Upcoming dividend ex-dates across watchlist with estimated dates, yields, and frequency", commands: ["dividend-calendar AAPL,MSFT,JNJ,KO"], mcpTool: "get_dividend_calendar", params: "tickers[]", icon: "💰" },
  { id: "spinoff_tracker", name: "Spin-off Tracker", phase: 63, category: "events", description: "Recent and upcoming spin-offs, special distributions, and unusual corporate events", commands: ["spinoff-tracker"], mcpTool: "track_spinoffs", params: "", icon: "🔄" },
  
  // Convertible Bond Arbitrage (Phase 64)
  { id: "convertible_scan", name: "Convertible Bond Scanner", phase: 64, category: "derivatives", description: "Scan for convertible bond arbitrage opportunities: high/low conversion premiums, implied vs realized volatility", commands: ["convertible-scan"], mcpTool: "scan_convertible_opportunities", params: "", icon: "🔄" },
  { id: "conversion_premium", name: "Conversion Premium Analysis", phase: 64, category: "derivatives", description: "Detailed conversion premium analysis: parity, conversion value, implied volatility calculation", commands: ["conversion-premium TSLA"], mcpTool: "analyze_conversion_premium", params: "ticker", icon: "💹" },
  { id: "convertible_arb", name: "Convertible Arbitrage", phase: 64, category: "derivatives", description: "Identify arbitrage strategies: conversion arbitrage, volatility arbitrage, gamma trading opportunities", commands: ["convertible-arb MSTR"], mcpTool: "analyze_arbitrage_opportunity", params: "ticker", icon: "⚖️" },
  { id: "convertible_greeks", name: "Convertible Greeks", phase: 64, category: "derivatives", description: "Calculate delta and gamma for convertible positions with hedge ratio recommendations", commands: ["convertible-greeks COIN"], mcpTool: "calculate_convertible_greeks", params: "ticker", icon: "📐" },
  
  // Sustainability-Linked Bonds (Phase 71)
  { id: "slb_market", name: "SLB Market Dashboard", phase: 71, category: "fixed-income", description: "Overall SLB market overview with risk breakdown, treasury yields, credit spreads, and at-risk bonds", commands: ["slb-market"], mcpTool: "get_slb_market", params: "", icon: "🌱" },
  { id: "slb_issuer", name: "SLB Issuer Analysis", phase: 71, category: "fixed-income", description: "Analyze specific issuer's SLB portfolio: bonds, KPI targets, current status, step-up exposure", commands: ["slb-issuer ENEL"], mcpTool: "analyze_slb_issuer", params: "ticker", icon: "🏢" },
  { id: "slb_kpi_tracker", name: "SLB KPI Tracker", phase: 71, category: "fixed-income", description: "Track upcoming KPI measurement dates, trigger events, urgency levels across all monitored SLBs", commands: ["slb-kpi-tracker"], mcpTool: "track_slb_kpis", params: "", icon: "📊" },
  { id: "slb_coupon_forecast", name: "SLB Coupon Forecast", phase: 71, category: "fixed-income", description: "Forecast potential coupon step-ups with probability-weighted expected coupons and cost impact", commands: ["slb-coupon-forecast"], mcpTool: "forecast_slb_coupons", params: "", icon: "📈" },
  
  // Short Squeeze Detector (Phase 65)
  { id: "squeeze_scan", name: "Short Squeeze Scanner", phase: 65, category: "alt-data", description: "Scan market for short squeeze candidates: high short interest, low float, rising volume, technical breakouts", commands: ["squeeze-scan --min-score 50 --limit 10"], mcpTool: "scan_squeeze_candidates", params: "min_score?, limit?, tickers?", icon: "🔥" },
  { id: "squeeze_score", name: "Squeeze Probability Score", phase: 65, category: "alt-data", description: "Calculate squeeze probability score (0-100) based on SI%, DTC, float, volume surge, technicals", commands: ["squeeze-score GME"], mcpTool: "calculate_squeeze_score", params: "ticker", icon: "🎯" },
  { id: "short_interest_detail", name: "Short Interest Analysis", phase: 65, category: "alt-data", description: "Detailed short interest metrics: shares short, SI% of float, days to cover, borrow cost estimates", commands: ["short-interest TSLA"], mcpTool: "get_short_interest_detail", params: "ticker", icon: "📊" },
  { id: "days_to_cover", name: "Days to Cover", phase: 65, category: "alt-data", description: "DTC analysis with squeeze risk assessment and estimated borrow costs", commands: ["days-to-cover AMC"], mcpTool: "calculate_days_to_cover", params: "ticker", icon: "⏱️" },
  
  // Market Regime Detection (Phase 66)
  { id: "market_regime", name: "Market Regime Detection", phase: 66, category: "quant", description: "Volatility clustering, correlation breakdowns, risk-on vs risk-off identification using VIX, cross-asset correlations, credit spreads", commands: ["market-regime", "regime-history", "risk-dashboard", "correlation-regime"], mcpTool: "get_market_regime", params: "action, lookback?", icon: "🎯" },
  
  // Correlation Anomaly Detector (Phase 87)
  { id: "corr_breakdown", name: "Correlation Breakdown Detection", phase: 87, category: "quant", description: "Detect unusual correlation breakdowns between asset pairs with Z-score anomaly flagging and directional breakdown analysis", commands: ["corr-breakdown --ticker1 AAPL --ticker2 MSFT"], mcpTool: "correlation_breakdown", params: "ticker1, ticker2, lookback?", icon: "📊" },
  { id: "corr_scan", name: "Correlation Matrix Scanner", phase: 87, category: "quant", description: "Scan correlation matrix for anomalies across multiple assets, identify significant correlation changes with severity scoring", commands: ["corr-scan --tickers SPY,TLT,GLD,QQQ"], mcpTool: "correlation_scan", params: "tickers[], lookback?", icon: "🔍" },
  { id: "corr_regime", name: "Correlation Regime Detection", phase: 87, category: "quant", description: "Detect market regime shifts via correlation structure changes (high/normal/low/decorrelated regimes) with volatility stability analysis", commands: ["corr-regime --tickers SPY,TLT,GLD,DBC"], mcpTool: "correlation_regime", params: "tickers[], lookback?", icon: "🔄" },
  { id: "corr_arbitrage", name: "Statistical Arbitrage Scanner", phase: 87, category: "quant", description: "Identify pairs with correlation breakdown for statistical arbitrage: cointegration analysis, mean reversion signals, trade recommendations", commands: ["corr-arbitrage --tickers XLF,XLK,XLE"], mcpTool: "correlation_arbitrage", params: "tickers[], lookback?", icon: "⚖️" },
  
  // Activist Success Predictor (Phase 67)
  { id: "activist_predict", name: "Activist Campaign Success Predictor", phase: 67, category: "alt-data", description: "ML model predicting activist campaign success probability using governance scores, ownership structure, and historical patterns", commands: ["activist-predict AAPL"], mcpTool: "predict_activist_success", params: "ticker", icon: "🎯" },
  { id: "activist_history", name: "Historical Campaign Analysis", phase: 67, category: "alt-data", description: "Analyze historical activist campaign patterns: success rates by market cap, sector, common demands, key success factors", commands: ["activist-history"], mcpTool: "get_activist_history", params: "", icon: "📊" },
  { id: "activist_targets", name: "Activist Target Scanner", phase: 67, category: "alt-data", description: "Scan for vulnerable activist targets by sector with success probability scoring and governance metrics", commands: ["activist-targets --sector Technology"], mcpTool: "scan_activist_targets", params: "sector?, min_cap?", icon: "🔍" },
  { id: "governance_score", name: "Governance Quality Score", phase: 67, category: "alt-data", description: "Company governance quality assessment (0-100 score) with ownership structure, board metrics, and vulnerability analysis", commands: ["governance-score MSFT"], mcpTool: "get_governance_score", params: "ticker", icon: "🏛️" },
  
  // 13D/13G Filing Alerts (Phase 68)
  { id: "filing_alerts_recent", name: "Recent Activist Filings", phase: 68, category: "events", description: "Real-time SEC EDGAR RSS feed for 13D/13G filings with filer details and target companies", commands: ["filing-alerts recent --hours 24", "filing-alerts recent --type 'SC 13D'"], mcpTool: "get_recent_filings", params: "filing_types?, hours?", icon: "🚨" },
  { id: "filing_alerts_search", name: "Company Filing Search", phase: 68, category: "events", description: "Search 13D/13G filings by company name with last 7 days of data", commands: ["filing-alerts search TESLA", "filing-alerts search AAPL --type '13D'"], mcpTool: "get_company_filings", params: "company_name, filing_types?", icon: "🔍" },
  { id: "filing_alerts_activists", name: "Active Filer Tracker", phase: 68, category: "events", description: "Identify active filers with multiple recent campaigns, target lists, and filing counts", commands: ["filing-alerts activists --min-filings 3"], mcpTool: "get_activist_filers", params: "min_filings?", icon: "🎯" },
  { id: "filing_alerts_watch", name: "Real-time Filing Monitor", phase: 68, category: "events", description: "Monitor SEC EDGAR RSS feeds for new activist filings (CLI only, polling-based)", commands: ["filing-alerts watch --interval 15 --iterations 4"], mcpTool: "watch_for_new_filings", params: "interval_minutes?, max_iterations?", icon: "👁️" },
  
  // Proxy Fight Tracker (Phase 69)
  { id: "proxy_filings", name: "Proxy Filings", phase: 69, category: "events", description: "Fetch proxy-related filings (DEF 14A, DEFA14A, 8-K) with document URLs and filing dates", commands: ["proxy-filings AAPL --years 3"], mcpTool: "fetch_proxy_filings", params: "ticker, years?", icon: "📑" },
  { id: "proxy_contests", name: "Proxy Contest Detection", phase: 69, category: "events", description: "Detect proxy contests by analyzing PREC14A and DEFC14A filings with contest status and timeline", commands: ["proxy-contests TSLA"], mcpTool: "detect_contested_proxies", params: "ticker", icon: "⚔️" },
  { id: "proxy_voting", name: "Voting Results", phase: 69, category: "events", description: "Fetch shareholder voting results from 8-K Item 5.07 filings (annual/special meeting outcomes)", commands: ["proxy-voting GOOGL"], mcpTool: "fetch_voting_results", params: "ticker", icon: "🗳️" },
  { id: "proxy_advisory", name: "Proxy Advisory Info", phase: 69, category: "events", description: "Information on ISS and Glass Lewis proxy advisory services with free alternatives", commands: ["proxy-advisory META"], mcpTool: "analyze_proxy_advisory", params: "ticker", icon: "📋" },
  { id: "proxy_summary", name: "Proxy Fight Summary", phase: 69, category: "events", description: "Comprehensive proxy analysis: recent filings, contest risk score (0-100), voting history, risk factors", commands: ["proxy-summary AAPL"], mcpTool: "proxy_summary", params: "ticker", icon: "📊" },
  
  // Greenwashing Detection (Phase 70)
  { id: "greenwashing_analysis", name: "Greenwashing Risk Analysis", phase: 70, category: "intelligence", description: "NLP analysis of ESG reports vs actual metrics: extract ESG claims from corporate disclosures, cross-reference with third-party ESG ratings and news controversies, detect inconsistencies between claims and reality, calculate 0-100 greenwashing risk score", commands: ["greenwashing AAPL --days 365"], mcpTool: "greenwashing_analysis", params: "ticker, days?", icon: "🌿" },
  { id: "greenwashing_compare", name: "Greenwashing Risk Comparison", phase: 70, category: "intelligence", description: "Compare greenwashing risk across multiple companies in same sector with side-by-side risk scoring, inconsistency counts, and ESG performance benchmarking", commands: ["greenwashing-compare TSLA XOM CVX BP --days 365"], mcpTool: "greenwashing_compare", params: "tickers[], days?", icon: "⚖️" },
  { id: "greenwashing_claims", name: "ESG Claims Extractor", phase: 70, category: "intelligence", description: "Extract ESG claims from corporate disclosures (10-K, sustainability reports) with claim type classification (target, achievement, commitment, policy), confidence scoring (0-100), and red flag detection for vague/aspirational language", commands: ["greenwashing-claims AAPL"], mcpTool: "greenwashing_claims", params: "ticker", icon: "📋" },
  { id: "greenwashing_inconsistencies", name: "Greenwashing Inconsistency Report", phase: 70, category: "intelligence", description: "Detailed inconsistency analysis showing gaps between ESG claims and reality: severity classification (HIGH/MEDIUM/LOW), evidence-based contradictions, third-party rating discrepancies, controversy tracking", commands: ["greenwashing-inconsistencies UBER"], mcpTool: "greenwashing_inconsistencies", params: "ticker", icon: "🚨" },
  
  // Climate Risk Scoring (Phase 72)
  { id: "climate_risk", name: "Climate Risk Score", phase: 72, category: "alt-data", description: "Composite climate risk scoring combining physical risks (floods, hurricanes, drought, wildfire) and transition risks (carbon pricing, regulation)", commands: ["climate-risk AAPL"], mcpTool: "get_climate_risk", params: "ticker", icon: "🌡️" },
  { id: "physical_risk", name: "Physical Climate Risk", phase: 72, category: "alt-data", description: "Physical climate risk exposure based on location and extreme weather patterns (NOAA/NASA data)", commands: ["physical-risk XOM"], mcpTool: "get_physical_risk", params: "ticker", icon: "🌊" },
  { id: "transition_risk", name: "Carbon Transition Risk", phase: 72, category: "alt-data", description: "Carbon transition risk from pricing, regulation, stranded assets, and sector carbon intensity (EPA data)", commands: ["transition-risk BP"], mcpTool: "get_transition_risk", params: "ticker", icon: "🏭" },
  { id: "carbon_scenario", name: "Carbon Scenario Analysis", phase: 72, category: "alt-data", description: "Scenario analysis for 1.5°C, 2°C, and 3°C warming pathways with carbon pricing impact projections", commands: ["carbon-scenario TSLA"], mcpTool: "get_carbon_scenario", params: "ticker", icon: "📈" },
  
  // Factor Timing Model (Phase 73)
  { id: "factor_timing", name: "Factor Timing Model", phase: 73, category: "quant", description: "Regime detection for when factors work (value, momentum, quality, size, low-vol), adaptive factor rotation based on macro indicators and market regimes", commands: ["factor-timing", "factor-rotation", "factor-performance 1y", "factor-regime-history --days 60"], mcpTool: "get_factor_timing", params: "action, period?, days?", icon: "🎯" },
  
  // ML Factor Discovery (Phase 74)
  { id: "ml_factor_discovery", name: "ML Factor Discovery", phase: 74, category: "quant", description: "Automated discovery of new predictive factors with feature engineering: auto-generate price, volume, momentum, volatility, fundamental factors; rank by Information Coefficient; walk-forward backtest with ML ensemble importance (RF, GBM, Lasso)", commands: ["discover-factors AAPL,MSFT,GOOGL", "factor-ic --top-n 20", "factor-backtest momentum_3m", "feature-importance"], mcpTool: "ml_factor_discovery", params: "action, tickers?, factor?, params?", icon: "🤖" },
  
  // AI Earnings Call Analyzer (Phase 76)
  { id: "ai_earnings_analyzer", name: "AI Earnings Call Analyzer", phase: 76, category: "intelligence", description: "Advanced LLM-powered earnings call analysis: real-time tone detection with contextual sentiment, hesitation pattern recognition (fillers, pauses, corrections), executive confidence scoring via multi-factor analysis, quarter-over-quarter language shift detection, advanced hedging language detection with categorization", commands: ["earnings-tone AAPL", "confidence-score TSLA", "language-shift MSFT", "hedging-detector NVDA"], mcpTool: "ai_earnings_analyzer", params: "action, ticker", icon: "🤖" },
  
  // Cross-Exchange Arbitrage (Phase 77)
  { id: "cross_exchange_arb", name: "Cross-Exchange Arbitrage", phase: 77, category: "quant", description: "Price discrepancy detection across NYSE, NASDAQ, IEX, CBOE exchanges with spread analysis, latency arbitrage opportunities, and historical profitability tracking", commands: ["arb-scan AAPL TSLA", "arb-spread AAPL", "arb-history TSLA --days 60", "exchange-latency"], mcpTool: "cross_exchange_arb", params: "action, symbols?, params?", icon: "🔄" },
  
  // PDF Report Exporter (Phase 79)
  { id: "pdf_exporter", name: "PDF Report Exporter", phase: 79, category: "infrastructure", description: "Convert markdown reports to professional PDF with charts and email delivery. Generate professional PDF reports from any module's output with headers, charts (matplotlib), tables, and branding. Support batch report generation and multiple templates.", commands: ["export-pdf AAPL --modules all", "export-pdf TSLA --modules earnings,technicals", "batch-report AAPL,MSFT,GOOGL", "report-template list"], mcpTool: "pdf_export", params: "action, ticker?, tickers?, modules?, template?", icon: "📄" },
  
  // Live Earnings Transcription (Phase 82)
  { id: "live_earnings", name: "Live Earnings Transcription", phase: 82, category: "intelligence", description: "Stream earnings calls, transcribe with Whisper, extract signals in real-time. Upcoming earnings calendar, audio transcription via OpenAI Whisper CLI, real-time sentiment/keyword/tone analysis, management confidence scoring, live trading alerts.", commands: ["calendar --days 30", "status", "simulate AAPL", "transcribe audio.mp3 --ticker AAPL"], mcpTool: "live_earnings", params: "action, ticker?, days?, audio_path?", icon: "🎤" },
  
  // Smart Data Prefetching (Phase 83)
  { id: "smart_prefetch", name: "Smart Data Prefetching", phase: 83, category: "infrastructure", description: "ML-based predictive data caching: tracks usage patterns across tickers, modules, time-of-day, and day-of-week to predict next queries. Preloads data during idle periods to improve cache hit rates. Time-weighted prediction for market hours, configurable prefetch pool size, and real-time hit rate monitoring.", commands: ["prefetch-stats", "prefetch-warmup", "cache-status", "prefetch-config --top 20 --confidence 0.6"], mcpTool: "smart_prefetch", params: "action, config?", icon: "🔮" },
  
  // Multi-Source Data Reconciliation (Phase 84)
  { id: "data_reconciliation", name: "Multi-Source Data Reconciliation", phase: 84, category: "infrastructure", description: "Cross-source data validation with confidence-weighted voting: compare prices across Yahoo Finance, CoinGecko, and FRED; flag discrepancies; implement confidence-based consensus; track source reliability over time; generate data quality reports with variance metrics and source rankings.", commands: ["reconcile-price AAPL", "reconcile-price BTC --type crypto", "data-quality-report", "source-reliability", "discrepancy-log --hours 24"], mcpTool: "data_reconciliation", params: "action, symbol?, type?, hours?", icon: "🔍" },
  
  // Portfolio Construction (Phase 81)
  { id: "portfolio_construction", name: "Portfolio Construction Tool", phase: 81, category: "quant", description: "Modern Portfolio Theory optimizer with Black-Litterman, ESG constraints, and tax-aware rebalancing: Markowitz mean-variance optimization for maximum Sharpe ratio portfolios, efficient frontier generation with visualization, Black-Litterman model integrating investor views, ESG-constrained optimization with minimum sustainability scores, tax-aware rebalancing with wash sale rule awareness and capital gains optimization, portfolio risk decomposition and factor attribution.", commands: ["mpt-optimize AAPL,MSFT,GOOGL --target-return 0.15 --esg-min 60", "efficient-frontier AAPL,TSLA,NVDA", "rebalance-plan", "portfolio-risk AAPL,MSFT,GOOGL --weights 0.33,0.33,0.34"], mcpTool: "portfolio_construction", params: "action, tickers?, target_return?, esg_min?, weights?", icon: "💼" },
  
  // Deep Learning Sentiment (Phase 88)
  { id: "finbert_earnings", name: "FinBERT Earnings Analysis", phase: 88, category: "intelligence", description: "Analyze earnings call transcripts with FinBERT deep learning model: entity-level sentiment, contextual understanding, positive/negative/neutral classification with confidence scores", commands: ["finbert-earnings AAPL"], mcpTool: "analyze_earnings_finbert", params: "ticker", icon: "🤖" },
  { id: "finbert_sec", name: "FinBERT SEC Filing Analysis", phase: 88, category: "intelligence", description: "Section-wise sentiment analysis of SEC filings (10-K, 10-Q, 8-K): Risk Factors, MD&A, Business overview with entity extraction and sentiment scoring", commands: ["finbert-sec TSLA 10-K"], mcpTool: "analyze_sec_finbert", params: "ticker, form_type?", icon: "📑" },
  { id: "finbert_news", name: "FinBERT News Sentiment", phase: 88, category: "intelligence", description: "Real-time news sentiment analysis with FinBERT: aggregate news from Yahoo Finance and Google News, entity-level sentiment, sentiment distribution, top headlines", commands: ["finbert-news MSFT 7"], mcpTool: "analyze_news_finbert", params: "ticker, days?", icon: "📰" },
  { id: "finbert_trend", name: "FinBERT Sentiment Trend", phase: 88, category: "intelligence", description: "Time-series sentiment analysis across multiple quarters: track sentiment evolution, detect trends (improving/declining/stable), sentiment volatility scoring", commands: ["finbert-trend NVDA 4"], mcpTool: "finbert_time_series", params: "ticker, quarters?", icon: "📊" },
  { id: "finbert_compare", name: "FinBERT Peer Comparison", phase: 88, category: "intelligence", description: "Compare sentiment across peer companies: rank by sentiment score, detailed results for each company, supports news/sec/earnings sources", commands: ["finbert-compare AAPL,MSFT,GOOGL news"], mcpTool: "compare_peer_finbert", params: "tickers[], source", icon: "⚖️" },
];
